-- Table structure for guohua_call_center_easy
-- ----------------------------
DROP TABLE IF EXISTS `guohua_call_center_easy`;
CREATE TABLE `guohua_call_center_easy` (
  `call_id` varchar(64) NOT NULL COMMENT '呼叫id',
  `contact_id` int(11) DEFAULT NULL COMMENT '联系人id',
  `customer_id` int(11) DEFAULT NULL COMMENT '客户id',
  `add_userid` varchar(64) DEFAULT NULL COMMENT '人员id',
  `add_time` datetime DEFAULT current_timestamp() COMMENT '添加时间',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `is_delete` tinyint(4) DEFAULT 1 COMMENT '是否删除 1否 0是',
  `accountId` varchar(255) DEFAULT NULL COMMENT '账户编号',
  `loginType` varchar(64) DEFAULT NULL COMMENT '坐席登录方式',
  `calloutType` varchar(64) DEFAULT NULL COMMENT '外呼方式:PSTN(坐席绑定手机号),SIP(sip话机)。\n外呼方式:PSTN(坐席绑定手机号),SIP(sip话机)。\n',
  `agentName` varchar(64) DEFAULT NULL COMMENT '坐席名称',
  `agentNumber` varchar(64) DEFAULT NULL COMMENT '坐席工号',
  `startTime` varchar(64) DEFAULT NULL COMMENT '呼叫开始时间',
  `answerTime` varchar(64) DEFAULT NULL COMMENT '接通时间',
  `hangupTime` varchar(64) DEFAULT NULL COMMENT '挂机时间',
  `callDuration` varchar(64) DEFAULT NULL COMMENT '通话时间 挂机时间-接通时间',
  `endTime` varchar(64) DEFAULT NULL COMMENT '呼叫结束时间',
  `callId` varchar(64) DEFAULT NULL COMMENT '通话ID',
  `callIdFrom` varchar(64) DEFAULT NULL COMMENT '转接到该通话的通话记录id',
  `transferFrom` varchar(64) DEFAULT NULL COMMENT '转接到该通话的坐席工号',
  `recordUrl` varchar(255) DEFAULT NULL COMMENT '通话录音文件地址',
  `leaveMsgUrl` varchar(255) DEFAULT NULL COMMENT '留言录音文件地址',
  `consultRecordUrl` varchar(255) DEFAULT NULL COMMENT '咨询录音文件地址',
  `action_id` varchar(64) DEFAULT NULL COMMENT '自定义参数，回调作为唯一id使用',
  `callType` varchar(64) DEFAULT NULL COMMENT '通话类型，呼入：''callin'', 外呼：''callout'', 双向呼叫：''twoWayCall'', 智能外呼：''autoCallout'', 外呼任务：''callTask'', 咨询：''consult'', 转接：''transfer'', 咨询转接：''consultTransfer''',
  `customerNumber` varchar(255) DEFAULT NULL COMMENT '客户号码，来电是主叫号码，去电是被叫号码',
  `customerProvince` varchar(64) DEFAULT NULL COMMENT '客户省份',
  `customerCity` varchar(64) DEFAULT NULL COMMENT '客户城市\n',
  `disNumber` varchar(64) DEFAULT NULL COMMENT '外显号，去电的主叫号码',
  `disProvince` varchar(64) DEFAULT NULL COMMENT '外显号省份',
  `disCity` varchar(64) DEFAULT NULL COMMENT '外显号城市\n',
  `serviceNumber` varchar(64) DEFAULT NULL COMMENT '服务号，来电的被叫号码\n',
  `queueName` varchar(64) DEFAULT NULL COMMENT '技能组名称\n',
  `queueNumber` varchar(64) DEFAULT NULL COMMENT '技能组编号\n',
  `inQueueTime` varchar(64) DEFAULT NULL COMMENT '进入队列时间\n',
  `queueDuration` varchar(64) DEFAULT NULL COMMENT '技能组排队等待时长 呼叫座席的时间-进入队列的时间\n',
  `eventId` varchar(64) DEFAULT NULL COMMENT '事件唯一ID\n',
  `failReason` varchar(64) DEFAULT NULL COMMENT '失败原因Key，如“1”。详情请参考附录1',
  `failReasonMsg` varchar(64) DEFAULT NULL COMMENT '失败原因值，如“未识别”。详情请参考\n',
  `numberGroupId` varchar(64) DEFAULT NULL,
  `numberGroupName` varchar(64) DEFAULT NULL,
  `hangUpParty` varchar(64) DEFAULT NULL COMMENT '挂机方 ''CUSTOMER''客户, ''AGENT''坐席, ''SYSTEM''系统',
  `satisfyStartTime` varchar(64) DEFAULT NULL COMMENT '满意度调查开始时间\n',
  `satisfyEndTime` varchar(64) DEFAULT NULL COMMENT '满意度调查结束时间\n',
  `satisfyDuration` int(11) DEFAULT NULL COMMENT '满意度调查时长 满意度结束时间-满意度开始时间\n',
  `satisfyKeys` varchar(64) DEFAULT NULL COMMENT '满意度按键值记录\n',
  `status` varchar(64) DEFAULT NULL COMMENT '通话状态：''CCR_LIMIT'':并发限制,''BLACK_LIMIT''黑名单限制,''ANSWER''已接听,''IVR''语音导航中挂机, ''QUEUE_ABANDON''排队放弃,''LEAVE_MSG''留言,''AGENT_NO_ANSWER''坐席未接听,''CUSTOMER_NO_ANSWER''客户未接听,''THREE_WAY_CALL'':三方,''TRANSFER''呼叫转移,''CONSULT''咨询已接听,''CONSULT_TRANSFER'': 咨询转移\n',
  `agentAnswerTime` varchar(64) DEFAULT NULL COMMENT '坐席接听时间',
  PRIMARY KEY (`call_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='极简外呼信息表';

-- ----------------------------
