-- Table structure for guohua_policy
-- ----------------------------
DROP TABLE IF EXISTS `guohua_policy`;
CREATE TABLE `guohua_policy` (
  `policy_id` int(11) NOT NULL AUTO_INCREMENT COMMENT '就业政策id',
  `department_id` int(11) DEFAULT NULL COMMENT '部门id',
  `city_id` int(11) DEFAULT NULL COMMENT '所在城市',
  `responsible_userid` varchar(64) DEFAULT NULL COMMENT '负责人',
  `base_is_have_cooperate` tinyint(4) DEFAULT NULL COMMENT '是否有合作 1是 0否',
  `base_is_support_cooperate` tinyint(4) DEFAULT NULL COMMENT '是否可以合作 1是 0否',
  `base_is_support_dispatch` tinyint(4) DEFAULT NULL COMMENT '是否支持本地派遣 1是 0否',
  `base_is_support_dispatch_gh` tinyint(4) DEFAULT NULL COMMENT '国华是否支持本地派遣 1是 0否',
  `base_min_money` decimal(10,2) DEFAULT NULL COMMENT '最低工资（元）',
  `base_min_money_start_date` varchar(255) DEFAULT NULL COMMENT '最低工资起始时间',
  `base_min_money_url` varchar(255) DEFAULT NULL COMMENT '最低工资链接',
  `base_average_money` decimal(10,2) DEFAULT NULL COMMENT '社平工资（元）',
  `base_basis_calculation` varchar(64) DEFAULT NULL COMMENT '企业平均人数计算标准',
  `base_levy_rate` decimal(10,2) DEFAULT NULL COMMENT '征收比例 ',
  `base_levy_formula` text DEFAULT NULL COMMENT '残保金计算公式',
  `base_levy_formula_other` text DEFAULT NULL COMMENT '残保金计算公式其他',
  `base_is_levy` tinyint(4) DEFAULT 1 COMMENT '是否强制征收税款  1是 0否',
  `base_is_pre_tax` tinyint(4) DEFAULT NULL COMMENT '是否是税前工资 1是 0 否',
  `base_min_money_standard` tinyint(4) DEFAULT NULL COMMENT '最低工资执行标准1应发 2实发',
  `base_is_dispatch` tinyint(4) DEFAULT NULL COMMENT '是否支持派遣   1是 0否',
  `base_is_replenish` tinyint(4) DEFAULT NULL COMMENT '是否支持补缴  1是  0否',
  `base_add_deadline_type` tinyint(4) DEFAULT NULL COMMENT '增员截止时间类型 1当月 2上月',
  `base_add_deadline` varchar(64) DEFAULT NULL COMMENT '增员截止时间',
  `base_less_deadline_type` tinyint(4) DEFAULT NULL COMMENT '减员截止时间类型 1当月 2上月',
  `base_less_deadline` varchar(64) DEFAULT NULL COMMENT '减员截止时间',
  `base_add_less_remarks` text DEFAULT NULL COMMENT '增减员备注',
  `base_subsidy_policies_url` text DEFAULT NULL COMMENT '补贴政策链接',
  `base_subsidy_description` text DEFAULT NULL COMMENT '补贴说明',
  `base_remarks` text DEFAULT NULL COMMENT '基本信息备注',
  `examine_way` tinyint(4) DEFAULT NULL COMMENT '审核方式 1网上审核',
  `examine_enterprise_assist` tinyint(4) DEFAULT NULL COMMENT '企业协助送审 1需要 0不需要',
  `examine_start_date` varchar(64) DEFAULT NULL COMMENT '审核开始时间',
  `examine_end_date` varchar(64) DEFAULT NULL COMMENT '审核结束时间',
  `examine_levy_start_date` varchar(64) DEFAULT NULL COMMENT '审核征收开始时间',
  `examine_levy_end_date` varchar(64) DEFAULT NULL COMMENT '审核征收结束时间',
  `examine_disabled_cert` tinyint(4) DEFAULT NULL COMMENT '残疾证原件 1需要 0不需要',
  `examine_employ_table` tinyint(4) DEFAULT NULL COMMENT '就业情况表 1需要 0不需要',
  `examine_idcard` tinyint(4) DEFAULT NULL COMMENT '身份证原件 1需要 0不需要',
  `examine_contract` tinyint(4) DEFAULT NULL COMMENT '劳动合同 1需要 0不需要',
  `examine_declar_records` tinyint(4) DEFAULT NULL COMMENT '报税记录 1需要 0不需要',
  `examine_security_records` tinyint(4) DEFAULT NULL COMMENT '社保缴纳记录 1需要 0不需要',
  `examine_onduty_cert` tinyint(4) DEFAULT NULL COMMENT '在岗证明 1需要 0不需要',
  `examine_salary_cert` tinyint(4) DEFAULT NULL COMMENT '工资发放凭证 1需要 0不需要',
  `examine_real_employ` tinyint(4) DEFAULT NULL COMMENT '是否查真实就业 1需要 0不需要',
  `examine_corporate_cert` tinyint(4) DEFAULT NULL COMMENT '企业承诺书 1需要 0不需要',
  `examine_other_material` varchar(64) DEFAULT NULL COMMENT '其他资料',
  `examine_remarks` varchar(255) DEFAULT '' COMMENT '审核要求备注',
  `material_subsidy_advice_tel` varchar(64) DEFAULT NULL COMMENT '政策咨询电话',
  `material_disabled_tel_url` text DEFAULT NULL COMMENT '残联通讯录链接',
  `policy_instructions_url` text DEFAULT NULL COMMENT '残疾人就业保障金征收使用管理办法链接',
  `policy_annually_url` text DEFAULT NULL COMMENT '残疾人就业保障金年审流程链接',
  `policy_mini_wage_url` text DEFAULT NULL COMMENT '最低工资链接',
  `policy_security_base_url` text DEFAULT NULL COMMENT '社保基数链接',
  `add_userid` varchar(255) DEFAULT '' COMMENT '添加人',
  `add_time` datetime DEFAULT current_timestamp() COMMENT '添加时间',
  `update_userid` varchar(255) DEFAULT '' COMMENT '更新人',
  `update_time` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp() COMMENT '更新时间',
  `is_delete` tinyint(4) DEFAULT 1 COMMENT '是否删除 1未删除 0已删除',
  `policy_status` tinyint(4) DEFAULT 1 COMMENT '政策状态 1正常 0草稿',
  PRIMARY KEY (`policy_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=134 DEFAULT CHARSET=utf8mb4 COMMENT='就业政策表';

-- ----------------------------
