-- Table structure for guohua_persons_match_wide
-- ----------------------------
DROP TABLE IF EXISTS `guohua_persons_match_wide`;
CREATE TABLE `guohua_persons_match_wide` (
  `persons_match_wide_id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '大宽表主键ID',
  `match_id` int(11) NOT NULL COMMENT '匹配ID',
  `persons_id` varchar(64) NOT NULL COMMENT '人员ID',
  `customer_id` int(11) DEFAULT NULL COMMENT '客户ID',
  `customer_name` varchar(255) DEFAULT NULL COMMENT '客户名称',
  `customer_source` varchar(10) DEFAULT NULL COMMENT '客户来源(1:FESCO 2:自销)',
  `customer_source_name` varchar(20) DEFAULT NULL COMMENT '客户来源名称',
  `customer_add_time` datetime DEFAULT NULL COMMENT '客户添加时间',
  `customer_status` int(11) DEFAULT NULL COMMENT '合同状态ID 1执行中 2 未开始 3已终止 4已结束''',
  `customer_status_name` varchar(255) DEFAULT NULL COMMENT '客户状态名称',
  `nature_name` varchar(255) DEFAULT NULL COMMENT '客户性质名称',
  `service_name` varchar(100) DEFAULT NULL COMMENT '客户客服负责人姓名',
  `responsible_name` varchar(100) DEFAULT NULL COMMENT '客户负责人姓名',
  `sign_account_id` int(11) DEFAULT NULL COMMENT '签约主体ID',
  `account_name` varchar(255) DEFAULT NULL COMMENT '签约主体名称',
  `contract_attribute` varchar(64) DEFAULT NULL COMMENT '合同属性(1:直雇 2:派遣)',
  `contract_attribute_name` varchar(20) DEFAULT NULL COMMENT '合同属性名称',
  `contract_name` varchar(255) DEFAULT NULL COMMENT '合同名称',
  `contract_money` decimal(10,2) DEFAULT NULL COMMENT '合同金额',
  `contract_end_date` date DEFAULT NULL COMMENT '合同结束时间',
  `product_type` int(11) DEFAULT NULL COMMENT '合同产品类型',
  `product_type_name` varchar(255) DEFAULT NULL COMMENT '合同产品类型名称',
  `sign_type` int(11) DEFAULT NULL COMMENT '签约类型 1新签 2续签',
  `light_num` int(11) DEFAULT 0 COMMENT '轻残人数',
  `weight_num` int(11) DEFAULT 0 COMMENT '重残人数',
  `light_price` decimal(10,2) DEFAULT NULL COMMENT '轻残报价/人',
  `weight_price` decimal(10,2) DEFAULT NULL COMMENT '重残报价/人',
  `persons_name` varchar(64) DEFAULT NULL COMMENT '姓名',
  `id_number` varchar(64) DEFAULT NULL COMMENT '身份证号',
  `birthday` varchar(32) DEFAULT NULL COMMENT '出生日期',
  `age` int(11) DEFAULT NULL COMMENT '年龄',
  `gender` tinyint(4) DEFAULT NULL COMMENT '性别(1:男 2:女)',
  `gender_name` varchar(10) DEFAULT NULL COMMENT '性别名称',
  `phone` varchar(64) DEFAULT NULL COMMENT '手机号',
  `nation_id` varchar(10) DEFAULT NULL COMMENT '民族ID',
  `marriage` varchar(10) DEFAULT NULL COMMENT '婚姻状况(1:已婚 2:未婚 3:离异)',
  `marriage_name` varchar(20) DEFAULT NULL COMMENT '婚姻状况名称',
  `education_id` int(11) DEFAULT NULL COMMENT '学历ID',
  `education_name` varchar(64) DEFAULT NULL COMMENT '学历名称',
  `is_city` varchar(10) DEFAULT NULL COMMENT '户口类型(1:城镇 2:农业)',
  `is_city_name` varchar(20) DEFAULT NULL COMMENT '户口类型名称',
  `permanent_address` varchar(255) DEFAULT NULL COMMENT '户籍地址',
  `current_address` varchar(255) DEFAULT NULL COMMENT '现住址',
  `disabled_type_id` tinyint(4) DEFAULT NULL COMMENT '残疾类别ID',
  `disabled_type_name` varchar(255) DEFAULT NULL COMMENT '残疾类别名称',
  `disabled_level` tinyint(4) DEFAULT NULL COMMENT '残疾等级(1,2,3,4)',
  `is_weight_disable` varchar(10) DEFAULT NULL COMMENT '是否重残(1:重残 2:轻残)',
  `is_weight_disable_name` varchar(20) DEFAULT NULL COMMENT '残疾程度名称',
  `disabled_no` varchar(64) DEFAULT NULL COMMENT '残疾证号',
  `disabled_receive_date` varchar(32) DEFAULT NULL COMMENT '残疾证发证日期',
  `disabled_no_remarks` varchar(255) DEFAULT NULL COMMENT '残疾证备注',
  `is_three_type` varchar(64) DEFAULT NULL COMMENT '是否三类人(1:是 0:否)',
  `bank_id` int(11) DEFAULT NULL COMMENT '银行ID',
  `bank_name` varchar(255) DEFAULT NULL COMMENT '银行名称',
  `account_bank` varchar(255) DEFAULT NULL COMMENT '开户行',
  `bank_number` varchar(64) DEFAULT NULL COMMENT '银行卡号',
  `social_status` varchar(255) DEFAULT NULL COMMENT '社保状态',
  `operation_dep_name` varchar(255) DEFAULT NULL COMMENT '运营部门名称(persons)',
  `company_name` varchar(255) DEFAULT NULL COMMENT '公司名称',
  `sale_dep_name` varchar(255) DEFAULT NULL COMMENT '销售部门名称',
  `store_name` varchar(255) DEFAULT NULL COMMENT '单店名称',
  `store_type_name` varchar(255) DEFAULT NULL COMMENT '基地类型名称',
  `store_level_name` varchar(255) DEFAULT NULL COMMENT '基地等级：0 普通 1 示范',
  `labor_manual` varchar(255) DEFAULT NULL COMMENT '劳动手册情况',
  `start_date` varchar(64) DEFAULT NULL COMMENT '合同开始日期',
  `end_date` varchar(64) DEFAULT NULL COMMENT '合同结束日期',
  `actual_end_date` varchar(64) DEFAULT NULL COMMENT '实际结束日期',
  `office_status` varchar(64) DEFAULT NULL COMMENT '入职状态(1:待入职 2:已入职 3:已离职)',
  `office_name` varchar(20) DEFAULT NULL COMMENT '入职状态名称',
  `is_crime` tinyint(4) DEFAULT NULL COMMENT '是否可用(1:可用 0:不可用)',
  `crime_remarks` varchar(255) DEFAULT NULL COMMENT '不可用原因',
  `create_time` datetime DEFAULT current_timestamp() COMMENT '创建时间',
  `update_time` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp() COMMENT '更新时间',
  `is_delete` tinyint(4) DEFAULT 1 COMMENT '是否删除(1:未删除 0:已删除)',
  PRIMARY KEY (`persons_match_wide_id`) USING BTREE,
  UNIQUE KEY `uk_match_id` (`match_id`),
  KEY `idx_persons_id` (`persons_id`),
  KEY `idx_customer_id` (`customer_id`),
  KEY `idx_office_status` (`office_status`),
  KEY `idx_is_delete` (`is_delete`),
  KEY `idx_customer_name` (`customer_name`),
  KEY `idx_persons_name` (`persons_name`),
  KEY `idx_id_number` (`id_number`),
  KEY `idx_create_time` (`create_time`),
  KEY `idx_update_time` (`update_time`)
) ENGINE=InnoDB AUTO_INCREMENT=105027 DEFAULT CHARSET=utf8mb4 COMMENT='人员匹配大宽表';

-- ----------------------------
