-- Table structure for guohua_emp_product
-- ----------------------------
DROP TABLE IF EXISTS `guohua_emp_product`;
CREATE TABLE `guohua_emp_product` (
  `product_id` bigint(20) NOT NULL COMMENT '产品ID（应用层 get_unique_num_id 生成）',
  `product_code` varchar(64) NOT NULL DEFAULT '' COMMENT '产品编码（业务编码，唯一）',
  `biz_side` tinyint(1) NOT NULL DEFAULT 1 COMMENT '业务端：1 toB企业端 2 toG政务端',
  `product_type` tinyint(4) NOT NULL DEFAULT 0 COMMENT '产品类型（对齐 base_dict_store_type.store_type）：1:公益劳动型 2:职康劳动型  3:居家就业型   4:产业融合型  ',
  `build_type` tinyint(1) NOT NULL DEFAULT 0 COMMENT 'toG产品类型1：0不适用 1自建 2共建 3自营',
  `product_attr` varchar(64) NOT NULL DEFAULT '' COMMENT '产品属性（标准/定制等）',
  `cust_province_code` varchar(6) NOT NULL DEFAULT '' COMMENT '客户区域-省 国标码 base_dict_region.std_code',
  `cust_city_code` varchar(6) NOT NULL DEFAULT '' COMMENT '客户区域-市 国标码 base_dict_region.std_code，空=全省',
  `cust_district_code` varchar(255) NOT NULL DEFAULT '0' COMMENT '客户区域-区 国标码，全市通用=0，多个逗号分隔（如顺义、昌平：110113,110114）',
  `cust_apply_scope` varchar(255) NOT NULL DEFAULT '' COMMENT '客户区域-适用范围文字描述（如：全市通用（不含苏州产业园区））',
  `delivery_region` varchar(500) NOT NULL DEFAULT '' COMMENT '产品交付所在地区（std_code，多个逗号分隔，来自原 region_type=2）',
  `delivery_region_desc` varchar(500) NOT NULL DEFAULT '' COMMENT '产品交付所在地区-文字描述（如：温州泰顺县、杭州淳安县）',
  `publish_status` tinyint(1) NOT NULL DEFAULT 0 COMMENT '发布状态：0草稿 1已发布 2已下架',
  `suit_disability` varchar(255) NOT NULL DEFAULT '' COMMENT '适配残疾人 字典id逗号分隔（如：101,102,103），关联 base_dict_emp_product_option.id（option_type=disability）',
  `suit_enterprise` varchar(500) NOT NULL DEFAULT '' COMMENT '适配企业/建设要求（如：全市企业，雇佣规模不低于5人，领取社会保险补贴）',
  `employ_form_id` int(11) NOT NULL DEFAULT 0 COMMENT '用工形式 字典id（option_type=employ_form）',
  `job_name_id` int(11) NOT NULL DEFAULT 0 COMMENT '岗位名称 字典id（option_type=job_name）',
  `salary multiple` decimal(10,2) NOT NULL DEFAULT 1.00 COMMENT '产品对应工资待遇倍数 默认 1',
  `salary_desc` varchar(500) NOT NULL DEFAULT '' COMMENT '工资待遇/待遇保障（自由文本，各地基数不同，如：到手工资不低于本市最低工资1.2倍，当前为3048元/人/月）',
  `work_time_id` int(11) NOT NULL DEFAULT 0 COMMENT '工作时间/工作时长 字典id（option_type=work_time）',
  `labor_project_id` int(11) NOT NULL DEFAULT 0 COMMENT '劳动项目/劳动产出 字典id（option_type=labor_project）',
  `price_option_id` int(11) NOT NULL DEFAULT 0 COMMENT '标准价格 字典id（option_type=price）',
  `price_min` decimal(10,2) NOT NULL DEFAULT 0.00 COMMENT '标准价格最低值（元/人/月，便于筛选排序）',
  `delivery_type_id` int(11) NOT NULL DEFAULT 0 COMMENT '企业端交付物 字典id（option_type=delivery_type）',
  `reserve_mild` int(11) NOT NULL DEFAULT 0 COMMENT '储备能力-轻残人数',
  `reserve_severe` int(11) NOT NULL DEFAULT 0 COMMENT '储备能力-重残人数',
  `reserve_ratio` varchar(32) NOT NULL DEFAULT '' COMMENT '配比要求/储备配比 轻残:重残（如 1:1、4:1）',
  `new_base_expand_time` varchar(64) NOT NULL DEFAULT '' COMMENT '新建基地（人员扩充）所需时间',
  `new_base_reserve_mild` varchar(64) NOT NULL DEFAULT '' COMMENT '单个新建基地储量-轻残',
  `new_base_reserve_severe` varchar(64) NOT NULL DEFAULT '' COMMENT '单个新建基地储量-重残',
  `min_person_num` varchar(32) NOT NULL DEFAULT '' COMMENT 'toG人员要求-最少人数（如：35、20-35、50-80）',
  `health_care_id` int(11) NOT NULL DEFAULT 0 COMMENT '健康关怀 字典id（option_type=health_care）',
  `training_id` int(11) NOT NULL DEFAULT 0 COMMENT '培训 字典id（option_type=training）',
  `care_activity_id` int(11) NOT NULL DEFAULT 0 COMMENT '关爱活动/融合活动 字典id（option_type=care_activity）',
  `entry_material_id` int(11) NOT NULL DEFAULT 0 COMMENT '入职办理-入职材料 字典id（option_type=entry_material）',
  `standard_delivery_time` text DEFAULT NULL COMMENT '入职办理-标准交付时间说明',
  `digital_services` varchar(2000) NOT NULL DEFAULT '' COMMENT '数字化服务 JSON，元素为字典id base_dict_emp_product_option.id：{"enterprise":[201,202],"store":[...],"disabled":[...],"cdpf":[...]} 键：enterprise企业端 store基地端 disabled残疾人端 cdpf残联监管端',
  `esg_exclusive_base` tinyint(1) NOT NULL DEFAULT 0 COMMENT 'ESG增值-专属基地：0不支持 1支持',
  `esg_charity_design` tinyint(1) NOT NULL DEFAULT 0 COMMENT 'ESG增值-公益项目设计：0不支持 1支持',
  `audit_time` varchar(255) NOT NULL DEFAULT '' COMMENT '审核服务-审核时间（如：3月1日-10月31日）',
  `special_audit_require` text DEFAULT NULL COMMENT '审核服务-特殊审核要求',
  `special_audit_material` text DEFAULT NULL COMMENT '审核服务-特殊审核材料',
  `audit_policy` text DEFAULT NULL COMMENT '政策列表-审核政策',
  `collection_policy` text DEFAULT NULL COMMENT '政策列表-征缴政策',
  `support_policy` text DEFAULT NULL COMMENT '政策列表-帮扶性就业政策',
  `research_topic_id` int(11) NOT NULL DEFAULT 0 COMMENT 'toG课题研究 字典id（option_type=research_topic）',
  `site_require` text DEFAULT NULL COMMENT 'toG基地建设-选址要求（面积/地区/残疾人资源要求）',
  `build_input_material` text DEFAULT NULL COMMENT 'toG基地建设-建设投入(物)（劳保用品、培训材料、宣传物料、挂牌等）',
  `build_input_fund` varchar(64) NOT NULL DEFAULT '' COMMENT 'toG基地建设-投入资金（如：30万以内、1000、5000）',
  `agreement_sign_id` int(11) NOT NULL DEFAULT 0 COMMENT 'toG基地建设-协议签署 字典id（option_type=agreement_sign）',
  `base_plaque` varchar(255) NOT NULL DEFAULT '' COMMENT 'toG基地建设-基地牌匾（命名规则）',
  `system_build` text DEFAULT NULL COMMENT 'toG基地建设-制度建立（依据文件等）',
  `org_structure` varchar(255) NOT NULL DEFAULT '' COMMENT 'toG基地建设-组织架构（如：管理人员配比1:6（含院长））',
  `base_record_id` int(11) NOT NULL DEFAULT 0 COMMENT 'toG基地建设-基地备案 字典id（option_type=base_record）',
  `schedule_attendance_id` int(11) NOT NULL DEFAULT 0 COMMENT 'toG基地运营-排班考勤 字典id（option_type=schedule_attendance）',
  `task_assign_id` int(11) NOT NULL DEFAULT 0 COMMENT 'toG基地运营-任务分配 字典id（option_type=task_assign）',
  `rights_protection_id` int(11) NOT NULL DEFAULT 0 COMMENT 'toG基地运营-权益保护 字典id（option_type=rights_protection）',
  `other_manage_id` int(11) NOT NULL DEFAULT 0 COMMENT 'toG基地运营-其他管理 字典id（option_type=other_manage）',
  `service_desc` text DEFAULT NULL COMMENT '服务说明',
  `service_remark` varchar(500) NOT NULL DEFAULT '' COMMENT '服务备注',
  `delivery_deadline` varchar(255) NOT NULL DEFAULT '' COMMENT '交付截止说明',
  `ext_json` text DEFAULT NULL COMMENT '扩展字段 JSON（特殊材料等后续新增需求先放这里，稳定后再提列）',
  `maintain_userid` varchar(64) NOT NULL DEFAULT '' COMMENT '维护人（企微userid）',
  `version_no` int(11) NOT NULL DEFAULT 1 COMMENT '版本号，每次发布+1',
  `sort` int(11) NOT NULL DEFAULT 9999 COMMENT '排序号',
  `create_userid` varchar(64) NOT NULL DEFAULT '' COMMENT '创建人',
  `update_userid` varchar(64) NOT NULL DEFAULT '' COMMENT '更新人',
  `is_delete` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否删除：0未删除 1已删除',
  `add_time` datetime NOT NULL DEFAULT current_timestamp() COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp() COMMENT '更新时间',
  PRIMARY KEY (`product_id`) USING BTREE,
  UNIQUE KEY `uk_emp_product_code` (`product_code`) USING BTREE,
  KEY `idx_emp_product_query` (`biz_side`,`product_type`,`publish_status`,`is_delete`) USING BTREE,
  KEY `idx_emp_product_cust_region` (`cust_province_code`,`cust_city_code`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='就业标准化产品主表（toB/toG 共用）';

-- ----------------------------
