-- Table structure for guohua_demand_0128
-- ----------------------------
DROP TABLE IF EXISTS `guohua_demand_0128`;
CREATE TABLE `guohua_demand_0128` (
  `demand_id` int(11) NOT NULL AUTO_INCREMENT COMMENT '需求id',
  `demand_sn` varchar(64) NOT NULL DEFAULT '' COMMENT '需求编号',
  `contract_id` bigint(20) NOT NULL DEFAULT 0 COMMENT '合同id',
  `project_id` bigint(20) NOT NULL DEFAULT 0 COMMENT '项目ID',
  `customer_id` bigint(20) NOT NULL DEFAULT 0 COMMENT '客户ID',
  `service_id` int(11) NOT NULL DEFAULT 0 COMMENT '服务ID',
  `job_id` int(11) DEFAULT NULL COMMENT '岗位id',
  `demand_people_num` int(11) NOT NULL COMMENT '总需求人数',
  `light_disability_num` int(11) NOT NULL DEFAULT 0 COMMENT '轻残人数',
  `severe_disability_num` int(11) NOT NULL DEFAULT 0 COMMENT '重残人数',
  `light_severe_prop` varchar(64) NOT NULL DEFAULT '' COMMENT '轻重残比(1:1 2:2)',
  `three_types_prop` int(11) NOT NULL DEFAULT 0 COMMENT '三类人员占比(%)',
  `demand_three_types_num` int(11) NOT NULL DEFAULT 0 COMMENT '需求三类人数',
  `is_payroll_agent` tinyint(4) NOT NULL DEFAULT 0 COMMENT '是否代发工资(1是 0否)',
  `is_tax_agent` tinyint(4) NOT NULL DEFAULT 0 COMMENT '是否代发个税(1是 0否)',
  `is_social_security` tinyint(4) NOT NULL DEFAULT 0 COMMENT '是否代交社保(1是 0否)',
  `is_provident_fund` tinyint(4) NOT NULL DEFAULT 0 COMMENT '是否代缴公积金(1是 0否)',
  `is_payment_fund` tinyint(4) NOT NULL DEFAULT 0 COMMENT '企业是否交公积金',
  `is_double` tinyint(4) NOT NULL DEFAULT 0 COMMENT '是否1.2倍工资发放（1是 0否）',
  `is_generate_bill` tinyint(4) NOT NULL DEFAULT 0 COMMENT '是否已生成账单(1是 0否)',
  `recruiting_status` tinyint(4) NOT NULL DEFAULT 0 COMMENT '招聘状态(0未开始 1招聘中 2已完成 3已关闭)',
  `responsible_person` varchar(255) NOT NULL DEFAULT '' COMMENT '负责人微信ID',
  `add_userid` varchar(255) NOT NULL DEFAULT '' COMMENT '添加人微信ID',
  `add_time` datetime NOT NULL DEFAULT current_timestamp() COMMENT '添加时间',
  `update_userid` varchar(255) NOT NULL DEFAULT '' COMMENT '更新人微信ID',
  `update_time` datetime NOT NULL DEFAULT current_timestamp() COMMENT '更新时间',
  `remarks` varchar(1000) NOT NULL DEFAULT '' COMMENT '备注',
  `is_delete` tinyint(4) NOT NULL DEFAULT 1 COMMENT '是否删除 1未删除 0 已删除',
  `tmp_id` varchar(255) NOT NULL DEFAULT '' COMMENT '临时id',
  `tmp_id2` varchar(255) NOT NULL DEFAULT '' COMMENT '临时服务id',
  `demand_name` varchar(255) NOT NULL DEFAULT '' COMMENT '需求名称',
  `audit_status` varchar(4) NOT NULL DEFAULT '0' COMMENT '审核状态 0待审核 1通过 2拒绝',
  `demand_delivery_time` date DEFAULT NULL COMMENT '需求交付时间',
  `finish_time` date DEFAULT NULL COMMENT '完成时间',
  `material_package` tinyint(4) DEFAULT NULL COMMENT '材料包类型 1内部 2外部',
  `is_medical_report` tinyint(4) DEFAULT 0 COMMENT '是否需要体检报告  1是0否',
  `is_customize_product` tinyint(4) DEFAULT 0 COMMENT '是否需要定制化劳动产品1是 0否',
  `base_type` tinyint(4) DEFAULT 2 COMMENT '基数类型 1主体 2城市',
  `base_type_account_id` int(11) DEFAULT 0 COMMENT '基数主体id',
  `base_type_region_id` int(11) DEFAULT 0 COMMENT '基数城市id',
  `sp_status` varchar(64) DEFAULT '0' COMMENT '审批状态',
  `sp_no` varchar(64) DEFAULT NULL COMMENT '审批标号',
  `backdating_remarks` varchar(255) DEFAULT NULL COMMENT '倒签原因',
  PRIMARY KEY (`demand_id`) USING BTREE,
  KEY `_index_service_id` (`service_id`) USING BTREE,
  KEY `_index_contract_id` (`contract_id`) USING BTREE,
  KEY `_index_job_id` (`job_id`) USING BTREE,
  KEY `_index_customer_id` (`customer_id`) USING BTREE,
  KEY `_index_demand_id` (`demand_id`) USING BTREE,
  KEY `_idx_recruiting_status` (`recruiting_status`) USING BTREE,
  KEY `idx_demand_is_delete` (`is_delete`),
  KEY `idx_demand_delete` (`is_delete`,`demand_id`),
  KEY `idx_demand_customer_id` (`customer_id`,`is_delete`)
) ENGINE=InnoDB AUTO_INCREMENT=20138 DEFAULT CHARSET=utf8mb4 COMMENT='就业管理系统-需求信息表';

-- ----------------------------
