-- Table structure for guohua_store_dashboard_monthly_snapshot
-- ----------------------------
DROP TABLE IF EXISTS `guohua_store_dashboard_monthly_snapshot`;
CREATE TABLE `guohua_store_dashboard_monthly_snapshot` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `stat_month` char(7) NOT NULL COMMENT '统计月份 YYYY-MM',
  `store_id` int(11) NOT NULL COMMENT '基地ID',
  `onsite_count` int(11) NOT NULL DEFAULT 0 COMMENT '在职人数',
  `light_onsite_count` int(11) NOT NULL DEFAULT 0 COMMENT '轻残在职人数',
  `weight_onsite_count` int(11) NOT NULL DEFAULT 0 COMMENT '重残在职人数',
  `bind_count` int(11) NOT NULL DEFAULT 0 COMMENT '已绑定人数',
  `checkin_person_count` int(11) NOT NULL DEFAULT 0 COMMENT '自然月内至少打卡一次的去重人数',
  `bound_checkin_person_count` int(11) NOT NULL DEFAULT 0 COMMENT '已绑定且当月打卡的人数（打卡率分子）',
  `checkin_active_person_count` int(11) NOT NULL DEFAULT 0 COMMENT '自然月内达到活跃标准人数',
  `rolling_30d_checkin_star_count` int(11) NOT NULL DEFAULT 0 COMMENT '计算时点近30天打卡之星人数',
  `new_onboard_count` int(11) NOT NULL DEFAULT 0 COMMENT '当月新增上岗人数',
  `onboard_target_count` int(11) NOT NULL DEFAULT 0 COMMENT '上岗落实分母：在职人数；类型3/4暂为0',
  `onboard_completed_count` int(11) NOT NULL DEFAULT 0 COMMENT '上岗落实分子：公益取当月有排班在职人数、职康取在职人数；类型3/4暂为0',
  `reserve_count` int(11) NOT NULL DEFAULT 0 COMMENT '储备潜力总人数',
  `light_reserve_count` int(11) NOT NULL DEFAULT 0 COMMENT '轻残储备人数',
  `weight_reserve_count` int(11) NOT NULL DEFAULT 0 COMMENT '重残储备人数',
  `schedule_required_count` int(11) NOT NULL DEFAULT 0 COMMENT '应排班次数',
  `schedule_completed_count` int(11) NOT NULL DEFAULT 0 COMMENT '已排班次数',
  `attendance_expected_count` int(11) NOT NULL DEFAULT 0 COMMENT '应出勤人次',
  `attendance_actual_count` int(11) NOT NULL DEFAULT 0 COMMENT '实到人次',
  `attendance_abnormal_count` int(11) NOT NULL DEFAULT 0 COMMENT '考勤异常人次',
  `attendance_should_count` int(11) NOT NULL DEFAULT 0 COMMENT '应打卡人次(入职日起工作日)',
  `attendance_workday_checkin_count` int(11) NOT NULL DEFAULT 0 COMMENT '实打卡人次(工作日内有打卡)',
  `attendance_out_range_count` int(11) NOT NULL DEFAULT 0 COMMENT '超范围人次(工作日内>20km)',
  `task_total_count` int(11) NOT NULL DEFAULT 0 COMMENT '工作任务总项数',
  `task_completed_count` int(11) NOT NULL DEFAULT 0 COMMENT '已完成任务项数',
  `task_checked_count` int(11) NOT NULL DEFAULT 0 COMMENT '已验收任务项数',
  `task_qualified_count` int(11) NOT NULL DEFAULT 0 COMMENT '验收合格任务项数',
  `task_audit_checked_count` int(11) NOT NULL DEFAULT 0 COMMENT '任务审核已审核数(ai_audit_status<>0，即AI已跑)',
  `task_audit_pass_count` int(11) NOT NULL DEFAULT 0 COMMENT '任务审核通过数(已审核且audit_status=10)',
  `task_audit_reject_count` int(11) NOT NULL DEFAULT 0 COMMENT '任务审核驳回数(已审核且audit_status=20)',
  `photo_required_count` int(11) NOT NULL DEFAULT 0 COMMENT '应上传工作照片人数或次数',
  `photo_completed_count` int(11) NOT NULL DEFAULT 0 COMMENT '已上传工作照片人数或次数',
  `photo_upload_person_count` int(11) NOT NULL DEFAULT 0 COMMENT '当月上传工作照去重人数',
  `agreement_required_count` int(11) NOT NULL DEFAULT 0 COMMENT '应上传协议基地数，单基地快照为0或1',
  `agreement_signed_count` int(11) NOT NULL DEFAULT 0 COMMENT '已上传协议基地数，单基地快照为0或1',
  `disabled_archive_required_count` int(11) NOT NULL DEFAULT 0 COMMENT '应完善残疾人档案人数',
  `disabled_archive_completed_count` int(11) NOT NULL DEFAULT 0 COMMENT '已完善残疾人档案人数',
  `operation_cover_required_count` int(11) NOT NULL DEFAULT 0 COMMENT '基地巡查应覆盖基地数，单基地为1',
  `operation_cover_completed_count` int(11) NOT NULL DEFAULT 0 COMMENT '基地巡查已覆盖基地数，单基地为0或1',
  `visit_record_count` int(11) NOT NULL DEFAULT 0 COMMENT '当月有效基地拜访记录数',
  `operation_standard_required_count` int(11) NOT NULL DEFAULT 0 COMMENT '运营达标应达标基地数，单基地为1',
  `operation_standard_completed_count` int(11) NOT NULL DEFAULT 0 COMMENT '运营达标已达标基地数：在职人数达等级门槛(自营50/示范35/普通20)为1',
  `phone_active_required_count` int(11) NOT NULL DEFAULT 0 COMMENT '电话活跃应完成数',
  `phone_active_completed_count` int(11) NOT NULL DEFAULT 0 COMMENT '电话活跃已完成数',
  `login_active_required_count` int(11) NOT NULL DEFAULT 0 COMMENT '基地登录活跃应覆盖基地数，单基地为1',
  `login_active_completed_count` int(11) NOT NULL DEFAULT 0 COMMENT '当月至少登录一次的基地数，单基地为0或1',
  `archive_required_count` int(11) NOT NULL DEFAULT 0 COMMENT '基地档案应完善数',
  `archive_completed_count` int(11) NOT NULL DEFAULT 0 COMMENT '基地档案已完善数',
  `reserve_target_count` int(11) NOT NULL DEFAULT 0 COMMENT '人员储备目标数',
  `reserve_completed_count` int(11) NOT NULL DEFAULT 0 COMMENT '人员储备完成数',
  `light_candidate_count` int(11) NOT NULL DEFAULT 0 COMMENT '轻残候选人数(persons_status=1)',
  `weight_candidate_count` int(11) NOT NULL DEFAULT 0 COMMENT '重残候选人数(persons_status=1)',
  `online_activity_required_count` int(11) NOT NULL DEFAULT 0 COMMENT '在线活动应参与人数',
  `online_activity_joined_count` int(11) NOT NULL DEFAULT 0 COMMENT '在线活动已参与人数',
  `labor_order_total_count` int(11) NOT NULL DEFAULT 0 COMMENT '劳动产品有效订单数',
  `labor_order_completed_count` int(11) NOT NULL DEFAULT 0 COMMENT '劳动产品已完成订单数',
  `labor_order_ongoing_count` int(11) NOT NULL DEFAULT 0 COMMENT '劳动产品进行中订单数',
  `labor_product_order_amount` decimal(16,2) NOT NULL DEFAULT 0.00 COMMENT '当月劳动产品有效订单金额',
  `labor_product_completed_amount` decimal(16,2) NOT NULL DEFAULT 0.00 COMMENT '当月劳动产品已完成金额',
  `labor_product_ongoing_amount` decimal(16,2) NOT NULL DEFAULT 0.00 COMMENT '当月劳动产品进行中金额',
  `labor_task_revenue_amount` decimal(16,2) NOT NULL DEFAULT 0.00 COMMENT '劳动任务收入',
  `labor_product_revenue_amount` decimal(16,2) NOT NULL DEFAULT 0.00 COMMENT '劳动产品订单收入',
  `operate_amount` decimal(16,2) NOT NULL DEFAULT 0.00 COMMENT '运营金额：当月OA审批通过的单店支出分摊(belong_month=stat_month)，是支出不是收入',
  `employment_amount` decimal(16,2) NOT NULL DEFAULT 0.00 COMMENT '就业金额：在职人员合同月服务费(年报价/12)，按当前时点计算，不随stat_month变化',
  `other_revenue_amount` decimal(16,2) NOT NULL DEFAULT 0.00 COMMENT '其他收入',
  `revenue_amount` decimal(16,2) NOT NULL DEFAULT 0.00 COMMENT '看板本月营收金额',
  `snapshot_status` tinyint(1) NOT NULL DEFAULT 0 COMMENT '状态：0计算中，1有效，2已封存，3失败',
  `is_finalized` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否封存：0否，1是',
  `data_version` int(11) NOT NULL DEFAULT 1 COMMENT '指标口径版本',
  `snapshot_batch_no` varchar(64) NOT NULL DEFAULT '' COMMENT '本次计算批次号',
  `calc_start_time` datetime DEFAULT NULL COMMENT '开始计算时间',
  `calc_end_time` datetime DEFAULT NULL COMMENT '计算完成时间',
  `error_message` varchar(500) NOT NULL DEFAULT '' COMMENT '最近计算错误',
  `add_time` datetime NOT NULL DEFAULT current_timestamp() COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp() COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_store_dashboard_month_store` (`stat_month`,`store_id`),
  KEY `idx_store_dashboard_store_month` (`store_id`,`stat_month`),
  KEY `idx_store_dashboard_month_status` (`stat_month`,`snapshot_status`,`is_finalized`)
) ENGINE=InnoDB AUTO_INCREMENT=1477 DEFAULT CHARSET=utf8mb4 COMMENT='基地月度公共指标快照表';

-- ----------------------------
