-- Table structure for guohua_store
-- ----------------------------
DROP TABLE IF EXISTS `guohua_store`;
CREATE TABLE `guohua_store` (
  `store_id` int(11) NOT NULL AUTO_INCREMENT COMMENT '单店id',
  `area_id` int(11) NOT NULL DEFAULT 0 COMMENT '地区id',
  `service_line_id` int(11) NOT NULL DEFAULT 0 COMMENT '业务线id',
  `store_type` tinyint(4) NOT NULL DEFAULT 0 COMMENT '单店类型 1:公益劳动型 2:职康劳动型  3:居家就业型   4:产业融合型   ',
  `store_name` varchar(255) NOT NULL DEFAULT '' COMMENT '单店名称',
  `ability_tags` varchar(1000) NOT NULL DEFAULT '' COMMENT '能力标签，多个标签使用英文逗号分隔',
  `store_short_name` varchar(255) NOT NULL DEFAULT '' COMMENT '单店简称',
  `guohua_manage_user` varchar(32) NOT NULL DEFAULT '' COMMENT '国华负责人',
  `disabled_manage_user` varchar(32) NOT NULL DEFAULT '' COMMENT '残联负责人',
  `guohua_phone` varchar(32) NOT NULL DEFAULT '' COMMENT '国华联系人电话',
  `township` varchar(64) NOT NULL DEFAULT '' COMMENT '所在乡镇',
  `is_show` tinyint(4) NOT NULL DEFAULT 1 COMMENT '是否显示 1显示 2不显示',
  `userid` varchar(64) NOT NULL DEFAULT '' COMMENT '企业微信用户id',
  `account_id` int(11) NOT NULL DEFAULT 0 COMMENT '对应账户ID',
  `amount` int(11) NOT NULL DEFAULT 0 COMMENT '工资金额',
  `is_flag` tinyint(4) DEFAULT 0 COMMENT '1 示范基地 2 自营标识 0 普通基地',
  `disabled_phone` varchar(32) NOT NULL DEFAULT '' COMMENT '残联联系人电话',
  `disabled_address` varchar(255) NOT NULL DEFAULT '' COMMENT '残联联系人地址',
  `disabled_name` varchar(32) NOT NULL DEFAULT '' COMMENT '残联联系人名称',
  `add_time` datetime DEFAULT current_timestamp() COMMENT '创建时间',
  `update_time` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp() COMMENT '更新时间',
  `establish_date` date NOT NULL COMMENT '基地建立日期',
  `agreement_start_date` date DEFAULT NULL COMMENT '协议有效期开始时间',
  `agreement_end_date` date DEFAULT NULL COMMENT '协议有效期结束时间',
  `is_face_clock` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否启用人脸识别打卡：0否，1是',
  `is_allow_clock` tinyint(1) NOT NULL DEFAULT 1 COMMENT '是否允许打卡：1允许，0禁止',
  `lat` decimal(10,6) DEFAULT NULL COMMENT '纬度',
  `lon` decimal(10,6) DEFAULT NULL COMMENT '经度',
  `detail_address` varchar(255) NOT NULL DEFAULT '' COMMENT '详情地址（省市区县+乡镇）',
  `store_operate_fee` decimal(10,2) DEFAULT NULL COMMENT '基地运营管理费用',
  `store_intro` varchar(2000) DEFAULT NULL COMMENT '基地简介',
  `base_rating` tinyint(4) NOT NULL DEFAULT 0 COMMENT '基地评级 1=A级示范基地 2=B级规范基地 3=C级合格基地 4=D级限制基地',
  `base_score` tinyint(3) unsigned DEFAULT NULL COMMENT '基地评分 1-100',
  `is_recommend` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否推荐：0否，1是',
  `recommend_sort` int(11) NOT NULL DEFAULT 0 COMMENT '推荐排序',
  `light_potential_num` int(11) NOT NULL DEFAULT 0 COMMENT '轻残潜力人数',
  `weight_potential_num` int(11) NOT NULL DEFAULT 0 COMMENT '重残潜力人数',
  `product_code` varchar(255) NOT NULL DEFAULT '' COMMENT '产品编码',
  `homeland_area` decimal(10,1) NOT NULL DEFAULT 0.0 COMMENT '面积',
  `principal` varchar(64) NOT NULL DEFAULT '' COMMENT '园长',
  `phone` varchar(32) NOT NULL DEFAULT '' COMMENT '电话',
  `wxacode_url` varchar(255) NOT NULL DEFAULT '' COMMENT '小程序码url',
  `homeland_organ_url` varchar(255) NOT NULL DEFAULT '' COMMENT '组织架构图片url',
  `map_url` varchar(255) NOT NULL DEFAULT '' COMMENT '地图url',
  `status` tinyint(4) NOT NULL DEFAULT 1 COMMENT '状态 1 启用 0 禁用',
  PRIMARY KEY (`store_id`) USING BTREE,
  KEY `_index_user_name` (`guohua_manage_user`) USING BTREE,
  KEY `index_is_show` (`is_show`) USING BTREE,
  KEY `idx_store_id_show` (`store_id`,`is_show`)
) ENGINE=InnoDB AUTO_INCREMENT=1785 DEFAULT CHARSET=utf8mb4 COMMENT='培就单店表';

-- ----------------------------
