-- Table structure for guohua_rel_contract_approval
-- ----------------------------
DROP TABLE IF EXISTS `guohua_rel_contract_approval`;
CREATE TABLE `guohua_rel_contract_approval` (
  `contract_id` int(11) NOT NULL AUTO_INCREMENT,
  `sp_no` varchar(255) NOT NULL DEFAULT '' COMMENT '审批编号',
  `sp_status` varchar(255) NOT NULL DEFAULT '0' COMMENT '审批状态',
  `contract_no` varchar(255) NOT NULL DEFAULT '' COMMENT '合同编号',
  `contract_name` varchar(255) NOT NULL DEFAULT '' COMMENT '合同名称',
  `contract_type_id` int(11) NOT NULL DEFAULT 0 COMMENT '合同类型ID 1单实体合同 2集团合同',
  `contract_status_id` int(11) NOT NULL DEFAULT 1 COMMENT '合同状态ID 1执行中 2 未开始 3已结束',
  `contract_attribute` varchar(64) NOT NULL DEFAULT '' COMMENT '合同属性 1:直雇 2:派遣',
  `contract_compensation` varchar(64) DEFAULT '1' COMMENT '合同赔偿 1:标准模板（无赔偿）2:标准赔偿 3:非标赔偿',
  `contract_source` varchar(64) DEFAULT NULL COMMENT '合同来源 1:就业合同 2:渠道合同',
  `customer_id` int(11) DEFAULT NULL COMMENT '客户ID',
  `contract_start_date` date DEFAULT NULL COMMENT '起始日期',
  `contract_end_date` date DEFAULT NULL COMMENT '终止日期',
  `service_line_id` int(11) NOT NULL COMMENT '业务线ID',
  `main_department_id` varchar(64) NOT NULL DEFAULT '' COMMENT '申请人部门',
  `contract_date` date DEFAULT NULL COMMENT '签约日期',
  `contract_remarks` varchar(500) NOT NULL DEFAULT '' COMMENT '备注',
  `add_userid` varchar(255) NOT NULL DEFAULT '' COMMENT '添加人ID',
  `add_time` datetime NOT NULL DEFAULT current_timestamp() COMMENT '提交时间',
  `update_userid` varchar(255) NOT NULL DEFAULT '' COMMENT '更新人ID',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `is_seal` tinyint(4) NOT NULL DEFAULT 1 COMMENT '是否用印 1是 2否',
  `is_delete` tinyint(4) NOT NULL DEFAULT 1 COMMENT '是否删除 1未删除 2已删除',
  `tmp_id` varchar(255) NOT NULL DEFAULT '' COMMENT '临时id',
  `contract_money` decimal(10,2) NOT NULL DEFAULT 0.00 COMMENT '合同金额',
  `payment_method` varchar(32) NOT NULL DEFAULT '' COMMENT '回款方式 1年付 2季度付 3月付 4一次性 5按比例 6按固定金额',
  `light_num` int(11) DEFAULT 0 COMMENT '轻残人数',
  `weight_num` int(11) DEFAULT 0 COMMENT '重残人数',
  `light_price` decimal(10,2) DEFAULT NULL COMMENT '轻残报价',
  `weight_price` decimal(10,2) DEFAULT NULL COMMENT '重残报价',
  `is_special` tinyint(4) NOT NULL DEFAULT 0 COMMENT '是否特殊1是 0否',
  `product_id` int(11) DEFAULT 0 COMMENT '产品id',
  `project_id` int(11) DEFAULT 0 COMMENT '项目id',
  `department_id` varchar(64) DEFAULT '' COMMENT '部门',
  `dispatch_service_payment_method` varchar(12) DEFAULT NULL COMMENT '派遣服务费回款方式 1年付 2季度付 3月付 7半年付',
  `dispatch_service_price` decimal(10,2) DEFAULT 0.00 COMMENT '派遣服务费单价 元/人/月',
  `dispatch_service_price_total` decimal(10,2) DEFAULT NULL COMMENT '派遣服务费总金额 合同周期计算',
  `opportunity_id` varchar(64) DEFAULT NULL COMMENT '商机id',
  `sign_type` tinyint(4) DEFAULT NULL COMMENT '签约类型 1新签 2续签',
  `sign_account_id` int(11) DEFAULT NULL COMMENT '签约主体id',
  `is_convert_dispatch` tinyint(4) DEFAULT NULL COMMENT '是否转国华派遣 1是 0否',
  `payment_subject_id` int(11) DEFAULT NULL COMMENT '付款主体',
  PRIMARY KEY (`contract_id`) USING BTREE,
  KEY `index_is_delete_` (`is_delete`) USING BTREE,
  KEY `index_sp_status_` (`sp_status`) USING BTREE,
  KEY `index_contract_no` (`contract_no`) USING BTREE,
  KEY `index_customer_id` (`customer_id`) USING BTREE,
  KEY `idx_contract_start_date` (`contract_start_date`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=13722 DEFAULT CHARSET=utf8mb4 COMMENT='合同信息表';

-- ----------------------------
