-- Table structure for guohua_persons
-- ----------------------------
DROP TABLE IF EXISTS `guohua_persons`;
CREATE TABLE `guohua_persons` (
  `persons_id` varchar(64) NOT NULL DEFAULT '' COMMENT '成员id',
  `ins_id` int(11) NOT NULL DEFAULT 0 COMMENT '机构id',
  `homeland_id` varchar(64) NOT NULL DEFAULT '' COMMENT '温馨家园id',
  `unionid` varchar(64) NOT NULL DEFAULT '' COMMENT '微信唯一id',
  `mini_openid` varchar(64) NOT NULL DEFAULT '' COMMENT '小程序openid',
  `mp_openid` varchar(64) NOT NULL DEFAULT '' COMMENT '公众号openid',
  `persons_name` varchar(64) NOT NULL DEFAULT '' COMMENT '姓名',
  `id_number` varchar(64) NOT NULL DEFAULT '' COMMENT '身份证号',
  `gender` tinyint(4) NOT NULL DEFAULT 1 COMMENT '性别 1男 2女',
  `phone` varchar(64) NOT NULL DEFAULT '' COMMENT '手机号',
  `tel` varchar(64) NOT NULL DEFAULT '' COMMENT '固定电话',
  `birthday` varchar(32) NOT NULL DEFAULT '' COMMENT '出生日期',
  `disabled_no` varchar(64) NOT NULL DEFAULT '' COMMENT '残疾证号',
  `marriage` varchar(10) NOT NULL DEFAULT '' COMMENT '婚姻情况 1 已婚 2未婚 3离异 4丧偶',
  `education_id` int(11) DEFAULT NULL COMMENT '学历id 教育程度',
  `native_place_id` varchar(32) NOT NULL DEFAULT '' COMMENT '籍贯id',
  `is_work` varchar(10) NOT NULL DEFAULT '' COMMENT '是否工作 1 已就业 2 未就业',
  `work_off_reason` varchar(255) NOT NULL DEFAULT '' COMMENT '下岗原因',
  `disabled_type_id` tinyint(4) NOT NULL DEFAULT 0 COMMENT '残疾类别id',
  `disabled_level` tinyint(4) NOT NULL DEFAULT 0 COMMENT '残疾等级 1,2,3,4',
  `is_weight_disable` varchar(10) NOT NULL DEFAULT '' COMMENT '是否是重残  1：重残 2：轻残',
  `nation_id` varchar(10) NOT NULL DEFAULT '' COMMENT '民族_id',
  `political_outlook` varchar(10) NOT NULL DEFAULT '' COMMENT '政治面貌 1党员 2群众 3:团员 0未填写',
  `community_ids` varchar(255) NOT NULL DEFAULT '' COMMENT '参数社群',
  `current_address` varchar(255) NOT NULL DEFAULT '' COMMENT '现住址地址',
  `lat` decimal(10,6) DEFAULT NULL COMMENT '纬度',
  `lon` decimal(10,6) DEFAULT NULL COMMENT '经度',
  `permanent_address` varchar(255) NOT NULL DEFAULT '' COMMENT '户籍地址',
  `precise_address` varchar(255) NOT NULL DEFAULT '' COMMENT '最精准地址(户籍省市区+现住址门牌,用于地理编码)',
  `email` varchar(128) NOT NULL DEFAULT '' COMMENT '邮箱',
  `head_img` varchar(100) NOT NULL DEFAULT '' COMMENT '头像',
  `is_city` varchar(10) NOT NULL DEFAULT '' COMMENT '户口类型 1非农业 2农业 0未填写',
  `is_other_disability` varchar(10) NOT NULL DEFAULT '' COMMENT '是否伴有其他残疾1 是 2否 0 未填写',
  `care_oneself` varchar(10) NOT NULL DEFAULT '' COMMENT '个人自理 1：可基本自理 2：需要人部分帮助 3：完全靠家人帮助',
  `add_time` datetime NOT NULL DEFAULT current_timestamp() COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp() COMMENT '更新时间',
  `occupation_cert` varchar(255) NOT NULL DEFAULT '' COMMENT '职业证书',
  `occupation_type` varchar(255) NOT NULL DEFAULT '' COMMENT '职业类别',
  `occupation_level` varchar(64) NOT NULL DEFAULT '' COMMENT '职业等级',
  `heath_history` varchar(255) NOT NULL DEFAULT '' COMMENT '既往康复历史',
  `personal_income_id` varchar(10) NOT NULL DEFAULT '' COMMENT '个人收入',
  `personal_income_other` varchar(255) NOT NULL DEFAULT '' COMMENT '个人收入其他',
  `medical_security_ids` varchar(255) NOT NULL DEFAULT '' COMMENT '医疗保障 可多选 1,2,3',
  `communication_mode` varchar(10) NOT NULL DEFAULT '' COMMENT '沟通方式 1口语 2非口语（如手势，眼神、怪异行为等）',
  `community_street` varchar(255) NOT NULL DEFAULT '' COMMENT '所在社区街道',
  `hope_heath` varchar(500) NOT NULL DEFAULT '' COMMENT '家人希望参加的康复项目',
  `nick_name` varchar(255) NOT NULL DEFAULT '' COMMENT '昵称',
  `avatar_url` varchar(255) NOT NULL DEFAULT '' COMMENT '头像',
  `points` int(11) NOT NULL DEFAULT 0 COMMENT '积分数',
  `pull_points` int(11) NOT NULL DEFAULT 0 COMMENT '拉新积分数',
  `invite_code` varchar(10) NOT NULL DEFAULT '' COMMENT '邀请码',
  `station_status` varchar(10) NOT NULL DEFAULT '' COMMENT '在站状态 1：已入站 2：已离站',
  `station_join_date` varchar(10) NOT NULL DEFAULT '' COMMENT '入站时间',
  `is_poor` varchar(2) NOT NULL DEFAULT '' COMMENT '是否贫困 1是 2否',
  `station_leave_date` varchar(10) NOT NULL DEFAULT '' COMMENT '离站时间',
  `is_account` varchar(2) NOT NULL DEFAULT '2' COMMENT '是否是台账导入',
  `account_homeland_id` varchar(36) NOT NULL DEFAULT '' COMMENT '台账所属homeland_id',
  `is_have_employ` varchar(64) NOT NULL DEFAULT '0' COMMENT '是否有就业信息 1:是 0:否',
  `audit_sn` varchar(20) NOT NULL DEFAULT '' COMMENT '审核编号',
  `audit_status` varchar(255) NOT NULL DEFAULT '2' COMMENT '人员审核状态 1未提交 2待审核  3审核通过  4审核异常',
  `persons_status` varchar(64) NOT NULL DEFAULT '4' COMMENT '人员状态 1:候选人 2:在职员工 3:离职员工:4在册人员',
  `office_status` varchar(64) NOT NULL DEFAULT '0' COMMENT '入职状态 1:待入职 2:已入职 3:已离职 0:未入职',
  `office_audit_status` varchar(64) NOT NULL DEFAULT '0' COMMENT '入职审核状态 1:未提交 2:已提交 3:待审核 4:审核通过 5:审核异常',
  `is_three_type` varchar(64) NOT NULL DEFAULT '0' COMMENT '是否三类人 1:是 0:否',
  `base_id` varchar(64) NOT NULL DEFAULT '' COMMENT '基地id',
  `is_delete` tinyint(4) NOT NULL DEFAULT 1 COMMENT '是否删除 1未删除 0已删除',
  `disabled_receive_date` varchar(32) NOT NULL DEFAULT '' COMMENT '残疾证发证日期',
  `is_disabled_expired` varchar(32) NOT NULL DEFAULT '2' COMMENT '残疾证是否过期 1是 2否',
  `social_status` varchar(255) NOT NULL DEFAULT '' COMMENT '社保状态',
  `persons_source` varchar(32) NOT NULL DEFAULT '' COMMENT '人员来源',
  `id_number_deadline` varchar(32) NOT NULL DEFAULT '' COMMENT '身份证有效期',
  `township` varchar(64) NOT NULL DEFAULT '' COMMENT '所在乡镇',
  `village` varchar(64) NOT NULL DEFAULT '' COMMENT '所在村',
  `is_base_help` varchar(255) NOT NULL DEFAULT '1' COMMENT '是否是帮扶性就业基地 ',
  `transfer_status` varchar(64) NOT NULL DEFAULT '' COMMENT '转签情况',
  `bus_reduction_name` varchar(64) NOT NULL DEFAULT '' COMMENT '公交减员名',
  `contract_return` varchar(64) NOT NULL DEFAULT '0' COMMENT '劳动合同是否返回 1是 0否',
  `social_card` varchar(64) NOT NULL DEFAULT '' COMMENT '社保卡',
  `social_card_describe` varchar(64) NOT NULL DEFAULT '' COMMENT '社保卡描述',
  `passwork_describe` varchar(64) NOT NULL DEFAULT '' COMMENT '存折描述',
  `tmp_card_describe` varchar(64) NOT NULL DEFAULT '' COMMENT '临时卡描述',
  `provident_card_describe` varchar(64) NOT NULL DEFAULT '' COMMENT '公积金卡描述',
  `first_push_date` varchar(64) DEFAULT NULL COMMENT '初次发证日期',
  `fesco_type` varchar(64) NOT NULL DEFAULT '' COMMENT '分类1 FESCO口径',
  `disabled_type` varchar(64) NOT NULL DEFAULT '' COMMENT '分类2 市残联口径',
  `belong_name` varchar(255) NOT NULL DEFAULT '' COMMENT '所属人/基地',
  `disabled_no_remarks` varchar(255) NOT NULL DEFAULT '' COMMENT '残疾证备注',
  `offsite_provident_card` varchar(64) NOT NULL DEFAULT '' COMMENT '外地公积金卡号',
  `remarks` varchar(255) NOT NULL DEFAULT '' COMMENT '多重备注',
  `low_income` tinyint(4) NOT NULL DEFAULT 0 COMMENT '是否是低收入 1是 0 否',
  `labor_manual` varchar(255) NOT NULL DEFAULT '' COMMENT '劳动手册情况',
  `shanghai_describe` varchar(255) NOT NULL DEFAULT '' COMMENT '上海描述信息',
  `retire_date` varchar(64) NOT NULL DEFAULT '' COMMENT '退休日期',
  `customer_id` int(11) NOT NULL DEFAULT 0 COMMENT '客户id',
  `customer_name` varchar(255) NOT NULL DEFAULT '' COMMENT '客户名称',
  `is_verify` varchar(255) NOT NULL DEFAULT '0' COMMENT '验证结果 1已验证 0未验证',
  `id_number_start` varchar(32) NOT NULL DEFAULT '' COMMENT '身份证开始日期',
  `id_number_end` varchar(32) NOT NULL DEFAULT '' COMMENT '身份证结束日期',
  `recommender` varchar(32) NOT NULL DEFAULT '' COMMENT '推荐人',
  `sign_status` tinyint(4) NOT NULL DEFAULT 0 COMMENT '是否参与转签  1:是 0:否',
  `contract_expire` varchar(32) NOT NULL DEFAULT '0' COMMENT '合同到期  1合同已到期',
  `disabled_start_date` varchar(32) DEFAULT NULL COMMENT '残疾证开始日期',
  `disabled_end_date` varchar(32) DEFAULT NULL COMMENT '残疾证结束日期',
  `verify_source_id` int(11) DEFAULT 1 COMMENT '验证来源id',
  `is_crime` tinyint(4) DEFAULT 1 COMMENT '是否可用  1可用  0不可用（犯罪、退休、低保等）',
  `is_checkin_disabled` tinyint(1) NOT NULL DEFAULT 1 COMMENT '是否可以打卡 1可以 0不可以',
  `crime_remarks` varchar(255) DEFAULT NULL COMMENT '不可用原因',
  `department_id` varchar(64) NOT NULL DEFAULT '' COMMENT '部门id',
  `persons_fund_base` int(11) DEFAULT NULL COMMENT '公积金基数',
  `age` int(11) DEFAULT 0 COMMENT '年龄',
  `userid` varchar(64) DEFAULT NULL COMMENT '负责人id',
  `fund_number` varchar(64) DEFAULT NULL COMMENT '公积金账号',
  `recommender_id` int(11) DEFAULT NULL COMMENT '关系户id',
  `persons_file_number` int(11) DEFAULT NULL COMMENT '员工档案号',
  `persons_introduce` varchar(255) DEFAULT NULL COMMENT '员工介绍',
  `work_content` varchar(255) DEFAULT NULL COMMENT '工作内容，月报用，手动脚本更新',
  `service_grade` char(1) NOT NULL DEFAULT '' COMMENT '残疾人服务分级 A/B/C，B级逻辑待定',
  `disabled_remarks` varchar(255) DEFAULT '' COMMENT '残疾证备注',
  `work_position_content_id` int(11) DEFAULT NULL,
  `citizen_card_no` varchar(100) DEFAULT NULL COMMENT '一卡通',
  PRIMARY KEY (`persons_id`) USING BTREE,
  KEY `index_community_ids_` (`community_ids`) USING BTREE,
  KEY `index_base_id` (`base_id`) USING BTREE,
  KEY `index_medical_security_ids_` (`medical_security_ids`) USING BTREE,
  KEY `index_id_number` (`id_number`) USING BTREE,
  KEY `idx_verify_source_id` (`verify_source_id`) USING BTREE,
  KEY `_index_persons_id` (`persons_id`) USING BTREE,
  KEY `_index_department_id` (`department_id`) USING BTREE,
  KEY `_index_customer_name` (`customer_name`) USING BTREE,
  KEY `idx_is_delete` (`is_delete`),
  KEY `idx_persons_id_is_delete` (`persons_id`,`is_delete`) USING BTREE,
  KEY `idx_persons_dept_status` (`department_id`,`persons_status`,`is_delete`),
  KEY `idx_persons_idnumber` (`id_number`,`is_delete`),
  KEY `idx_persons_base` (`base_id`,`is_delete`),
  KEY `idx_persons_base_delete_status` (`base_id`,`is_delete`,`persons_status`),
  KEY `idx_department_status` (`department_id`,`persons_status`,`is_delete`),
  KEY `idx_b_idno_del` (`id_number`,`is_delete`),
  KEY `idx_persons_delete_idno` (`is_delete`,`id_number`),
  KEY `idx_gp_base_del_status_pid` (`base_id`,`is_delete`,`persons_status`,`persons_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='残疾人表';

-- ----------------------------
