-- Table structure for guohua_customer_salary
-- ----------------------------
DROP TABLE IF EXISTS `guohua_customer_salary`;
CREATE TABLE `guohua_customer_salary` (
  `salary_id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '薪资id',
  `salary_sn` varchar(255) DEFAULT NULL COMMENT '账单编号',
  `customer_id` int(11) NOT NULL DEFAULT 0 COMMENT '客户id',
  `contract_id` int(11) DEFAULT NULL COMMENT '合同id',
  `demand_id` int(11) DEFAULT NULL COMMENT '需求id',
  `salary_month` date DEFAULT NULL COMMENT '薪资发放月份',
  `company_salary` decimal(19,2) NOT NULL DEFAULT 0.00 COMMENT '薪资',
  `persons_nums` int(11) NOT NULL DEFAULT 0 COMMENT '当月发放人数',
  `total_money` decimal(10,2) NOT NULL DEFAULT 0.00 COMMENT '当月发放工资总金额',
  `total_real_money` decimal(10,2) DEFAULT NULL COMMENT '应发工资总额',
  `company_social_insurance_total` decimal(10,2) NOT NULL DEFAULT 0.00 COMMENT '单位社保合计',
  `persons_social_insurance_total` decimal(10,2) NOT NULL DEFAULT 0.00 COMMENT '个人社保合计',
  `company_housing_total` decimal(10,2) NOT NULL DEFAULT 0.00 COMMENT '单位公积金合计',
  `persons_housing_total` decimal(10,2) NOT NULL DEFAULT 0.00 COMMENT '个人公积金合计',
  `service_price_total` decimal(10,2) NOT NULL DEFAULT 0.00 COMMENT '服务费合计',
  `dispatch_service_price_total` decimal(10,2) DEFAULT 0.00 COMMENT '派遣服务费合计',
  `other_performance_price_total` decimal(10,2) DEFAULT 0.00 COMMENT '其他绩效合计',
  `other_price_total` decimal(10,2) NOT NULL DEFAULT 0.00 COMMENT '其他费用',
  `other_discrepancy_total` decimal(10,2) DEFAULT 0.00 COMMENT '补款',
  `status` tinyint(4) NOT NULL DEFAULT 1 COMMENT '账单确认状态：1待确认  2已确认',
  `customer_confirm_status` tinyint(4) NOT NULL DEFAULT 0 COMMENT '客户确认状态 0未确认 1已确认',
  `remarks` varchar(1000) NOT NULL DEFAULT '' COMMENT '备注信息',
  `add_time` datetime NOT NULL DEFAULT current_timestamp() COMMENT '记录生成时间',
  `update_time` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp() COMMENT '更新时间',
  `is_delete` tinyint(4) NOT NULL DEFAULT 1 COMMENT '1:未删除 0：已删除',
  `is_min` tinyint(4) NOT NULL DEFAULT 2 COMMENT '是否为最低工资1:是 2:否',
  `company_old_rate` varchar(11) NOT NULL DEFAULT '' COMMENT '企业养老',
  `persons_old_rate` varchar(11) NOT NULL DEFAULT '' COMMENT '自身养老',
  `company_medical_rate` varchar(11) NOT NULL DEFAULT '' COMMENT '企业医疗',
  `persons_medical_rate` varchar(11) NOT NULL DEFAULT '' COMMENT '自身医疗',
  `company_injury_rate` varchar(11) NOT NULL DEFAULT '' COMMENT '企业工伤',
  `persons_injury_rate` varchar(11) NOT NULL DEFAULT '' COMMENT '自身工伤',
  `company_work_rate` varchar(11) NOT NULL DEFAULT '' COMMENT '企业失业',
  `persons_work_rate` varchar(11) NOT NULL DEFAULT '' COMMENT '自身失业',
  `company_medicine_heavy_rate` varchar(11) NOT NULL DEFAULT '0' COMMENT '企业大病医疗',
  `persons_medicine_heavy_rate` varchar(11) NOT NULL DEFAULT '0' COMMENT '自身大病医疗',
  `is_salary` tinyint(4) NOT NULL DEFAULT 2 COMMENT '是否含个人社保 1:是  2:否',
  `social_security_base` float(11,2) NOT NULL DEFAULT 0.00 COMMENT '社保缴纳基数',
  `company_fund_rate` varchar(11) NOT NULL DEFAULT '' COMMENT '公积金比例5%-12%',
  `is_provident_fund` int(11) NOT NULL DEFAULT 0 COMMENT '企业是否承担个人公积金 1是 0否',
  `company_fund_base` float NOT NULL DEFAULT 0 COMMENT '公积金缴纳基数',
  `is_payment_fund` tinyint(4) NOT NULL DEFAULT 1 COMMENT '企业是否交公积金 1是 0否',
  `is_double` tinyint(4) NOT NULL DEFAULT 0 COMMENT '是否1.2倍发放 1是 0否',
  `is_social_security` tinyint(4) NOT NULL DEFAULT 1 COMMENT '企业是否承担个人社保 1是 0否',
  `performance_salary_total` decimal(10,2) DEFAULT NULL COMMENT '其他补贴合计',
  `bill_id` int(11) DEFAULT NULL COMMENT '开票申请id',
  `seal_id` int(11) DEFAULT NULL COMMENT '用印申请id',
  `payment_confirm_id` int(11) DEFAULT NULL COMMENT '关联到款id',
  `dispatch_wages_id` varchar(64) DEFAULT NULL COMMENT '发薪申请id',
  `total` decimal(10,2) DEFAULT NULL COMMENT '收费总额',
  `five_social_fund_total` decimal(10,2) DEFAULT NULL COMMENT '五险一金补扣',
  `old_base` float(11,2) NOT NULL DEFAULT 0.00 COMMENT '养老基数',
  `medical_base` float(11,2) NOT NULL DEFAULT 0.00 COMMENT '医疗基数',
  `injury_base` float(11,2) NOT NULL DEFAULT 0.00 COMMENT '工伤基数',
  `work_base` float(11,2) NOT NULL DEFAULT 0.00 COMMENT '失业基数',
  `medicine_heavy_base` float(11,2) NOT NULL DEFAULT 0.00 COMMENT '大病医疗基数',
  `is_send` int(11) DEFAULT 0 COMMENT '1已发送 0未发送',
  `company_medical_base` decimal(11,1) DEFAULT NULL COMMENT '医疗基数',
  `product_amount` decimal(11,2) NOT NULL DEFAULT 0.00 COMMENT '劳动产品金额',
  `fusion_activity_fees` decimal(11,2) NOT NULL DEFAULT 0.00 COMMENT '融合活动费用',
  PRIMARY KEY (`salary_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=43040 DEFAULT CHARSET=utf8mb4 COMMENT='客户薪资管理表';

-- ----------------------------
