-- Table structure for guohua_bill
-- ----------------------------
DROP TABLE IF EXISTS `guohua_bill`;
CREATE TABLE `guohua_bill` (
  `bill_id` int(11) NOT NULL AUTO_INCREMENT COMMENT '账单发票id',
  `customer_id` int(11) NOT NULL COMMENT '客户id',
  `payment_confirm_id` int(11) NOT NULL DEFAULT 0 COMMENT '确认id',
  `pay_company_name` varchar(255) NOT NULL DEFAULT '' COMMENT '付款单位',
  `account_id` int(11) NOT NULL COMMENT '开票公司；base_dict_account',
  `department_id` varchar(64) NOT NULL DEFAULT '' COMMENT '子部门id',
  `main_department_id` int(11) NOT NULL COMMENT '主部门id',
  `service_line_id` int(11) NOT NULL COMMENT '业务线id',
  `product_id` int(11) NOT NULL COMMENT '产品id',
  `project_id` int(11) NOT NULL COMMENT '项目id',
  `store_id` varchar(255) NOT NULL DEFAULT '' COMMENT '单店id',
  `bill_type` tinyint(4) NOT NULL DEFAULT 0 COMMENT '发票类型：0:增值税普通发票；1:增值税专用发票',
  `bill_content_id` int(11) NOT NULL DEFAULT 0 COMMENT '发票内容id',
  `bill_amount` decimal(11,2) NOT NULL COMMENT '开票金额',
  `is_cp_amount` tinyint(4) NOT NULL DEFAULT 0 COMMENT '是否含代收代付 1含 0 不含',
  `sb_amount` decimal(11,2) NOT NULL DEFAULT 0.00 COMMENT '社保费用',
  `gjx_amount` decimal(11,2) NOT NULL DEFAULT 0.00 COMMENT '公积基金费用',
  `gz_amount` decimal(11,2) NOT NULL DEFAULT 0.00 COMMENT '工资费用',
  `fw_amount` decimal(11,2) NOT NULL DEFAULT 0.00 COMMENT '服务费用',
  `remarks` varchar(1000) NOT NULL DEFAULT '' COMMENT '备注',
  `confirm_amount` decimal(11,2) DEFAULT 0.00 COMMENT '已认领总金额',
  `confirm_ids` varchar(255) DEFAULT NULL COMMENT '已认领id（认款表id）',
  `is_confirm` tinyint(4) NOT NULL DEFAULT 0 COMMENT '是否认领 1已认领 0未认领',
  `userid` varchar(64) NOT NULL DEFAULT '' COMMENT '申请人id',
  `sp_no` varchar(255) NOT NULL DEFAULT '' COMMENT '审批编号',
  `sp_status` tinyint(4) NOT NULL DEFAULT 1 COMMENT '审批状态。4已撤销，3已驳回，2已通过，1审批中',
  `add_time` datetime NOT NULL DEFAULT current_timestamp() COMMENT '添加时间',
  `is_delete` tinyint(4) NOT NULL DEFAULT 1 COMMENT '是否删除 1未删除 0已删除',
  `product_data` varchar(255) NOT NULL DEFAULT '' COMMENT '产品层级id',
  `is_receive` tinyint(4) NOT NULL DEFAULT 0 COMMENT '是否领取发票 1已领取 0未领取',
  `is_claim` tinyint(4) NOT NULL DEFAULT 0 COMMENT '是否已开 1已开 0未开',
  `salary_id` varchar(255) NOT NULL DEFAULT '0' COMMENT '薪资id',
  `contract_id` int(11) DEFAULT NULL COMMENT '合同id',
  `payment_plan_id` varchar(500) DEFAULT NULL COMMENT '回款计划id',
  `seal_type` varchar(255) DEFAULT NULL COMMENT '印章类型',
  `is_seal` tinyint(4) DEFAULT NULL COMMENT '是否用印1是 0否',
  `invoice_status` tinyint(4) DEFAULT 1 COMMENT '发票状态 1正常 0作废',
  `is_rebill` tinyint(4) DEFAULT NULL COMMENT '是否重开1是 0否',
  PRIMARY KEY (`bill_id`) USING BTREE,
  KEY `index_customer_id` (`customer_id`) USING BTREE,
  KEY `index_sp_status` (`sp_status`,`is_delete`) USING BTREE,
  KEY `idx_bill_composite` (`bill_id`,`sp_status`,`is_delete`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=20574 DEFAULT CHARSET=utf8mb4 COMMENT='开票信息表';

-- ----------------------------
