-- Table structure for guohua_call_center_ruoyun
-- ----------------------------
DROP TABLE IF EXISTS `guohua_call_center_ruoyun`;
CREATE TABLE `guohua_call_center_ruoyun` (
  `call_id` varchar(64) NOT NULL COMMENT '呼叫id',
  `_id` varchar(64) DEFAULT NULL COMMENT '通话记录ID ',
  `superUniqueId` varchar(64) DEFAULT NULL COMMENT '通话记录ID',
  `contact_id` int(11) DEFAULT NULL COMMENT '联系人id',
  `customer_id` int(11) DEFAULT NULL COMMENT '客户id',
  `add_userid` varchar(64) DEFAULT NULL COMMENT '人员id',
  `add_time` datetime DEFAULT current_timestamp() COMMENT '添加时间',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `accountId` varchar(64) DEFAULT NULL COMMENT '账户ID',
  `agentName` varchar(64) DEFAULT NULL COMMENT '座席名称',
  `agentNumber` varchar(64) DEFAULT NULL COMMENT '座席工号',
  `agentTimeout` int(11) DEFAULT NULL COMMENT '主叫超时时长，默认60秒',
  `calleeTimeout` int(11) DEFAULT NULL COMMENT '被叫超时时长，默认60秒',
  `calleeNumber` varchar(64) DEFAULT NULL COMMENT '被叫号码',
  `loginType` varchar(64) DEFAULT NULL COMMENT '登录方式（PSTN: 手机;SIP: 话机）',
  `startTime` varchar(64) DEFAULT NULL COMMENT '开始呼叫时间',
  `consultRecordUrl` varchar(255) DEFAULT NULL COMMENT '咨询录音地址',
  `callDuration` int(11) DEFAULT NULL COMMENT '通话时长',
  `satisfyKeys` varchar(64) DEFAULT NULL COMMENT '满意度按键值记录 ',
  `serviceNumber` varchar(64) DEFAULT NULL COMMENT '服务号|中继号 ',
  `transferFrom` varchar(64) DEFAULT NULL COMMENT '被转接座席工号',
  `answerTime` varchar(255) DEFAULT NULL COMMENT '被叫摘机时间 ',
  `inQueueTime` varchar(255) DEFAULT NULL COMMENT '开始排队时间',
  `callerProvince` varchar(64) DEFAULT NULL COMMENT '外显号归属省',
  `callerCity` varchar(64) DEFAULT NULL COMMENT '外显归属市',
  `satisfyEndTime` varchar(64) DEFAULT NULL COMMENT '满意度结束时间',
  `customerNumber` varchar(64) DEFAULT NULL COMMENT '客户号码',
  `customerCity` varchar(64) DEFAULT NULL,
  `customerProvince` varchar(64) DEFAULT NULL COMMENT '客户号码归属地',
  `customerCountry` varchar(64) DEFAULT NULL COMMENT '客户号码所属国家',
  `customerCountryCode` varchar(64) DEFAULT NULL COMMENT '客户号码所属国家编码',
  `callType` varchar(64) DEFAULT NULL COMMENT '类型：''incoming'':呼入,''dialout'': "外呼",''webcall'':webcall,''transfer'':转接,''consultTransfer'':咨询转接,''consult'':咨询,''listen'':监听,''whisper'':耳语,''previewDialout'':预览外呼,''autoDialout'':自动外呼,''breakIn'':强插,''AXB'':AXB呼叫,''ipPhonesDialout'':话机外呼,''directDialout'':号码独售外呼',
  `hangupTime` varchar(64) DEFAULT NULL COMMENT '第一方挂机时间',
  `hangUpParty` varchar(64) DEFAULT NULL COMMENT '第一挂机方',
  `satisfyDuration` int(11) DEFAULT NULL COMMENT '满意度耗时时长',
  `eventId` varchar(64) DEFAULT NULL COMMENT '事件ID ',
  `recordDuration` int(11) DEFAULT NULL,
  `recordUrl` varchar(255) DEFAULT NULL COMMENT '通话录音地址',
  `leaveMsgUrl` varchar(255) DEFAULT NULL COMMENT '留言录音地址',
  `queueName` varchar(128) DEFAULT NULL COMMENT '技能组名称',
  `queueDuration` int(11) DEFAULT NULL COMMENT '技能组排队时长',
  `callerNumber` varchar(64) DEFAULT NULL COMMENT '外显号',
  `queueNumber` varchar(64) DEFAULT NULL COMMENT '技能组编号',
  `endTime` varchar(64) DEFAULT NULL COMMENT '通话结束时间',
  `satisfyStartTime` varchar(255) DEFAULT NULL COMMENT '满意度开始时间',
  `status` varchar(255) DEFAULT NULL COMMENT '状态：''CALL_LIMITE'':并发限制,''BLACK_LIST''黑名单限制,''ANSWER''已接听,''IVR''语音导航中挂机, ''QUEUE_ABANDON''排队放弃,''VOICEMAIL''留言,''AGENT_NO_ANSWER''座席未接听,''CUSTOMER_NO_ANSWER''客户未接听,''CALL_THREEWAY'':三方,''CALL_TRANSFER''呼叫转移,''CALL_CONSULT''咨询已接听,''CALL_CONSULT_TRANSFER'': 咨询转移',
  `extras` varchar(64) DEFAULT NULL COMMENT '自定义参数',
  `is_delete` tinyint(4) DEFAULT 1 COMMENT '是否删除 1否 0是',
  `displayNumber` varchar(64) DEFAULT NULL,
  `statusNumber` varchar(64) DEFAULT NULL,
  `trunkNumber` varchar(64) DEFAULT NULL,
  `number` varchar(64) DEFAULT NULL,
  `initStatusName` varchar(64) DEFAULT NULL,
  `customerAreaCode` varchar(64) DEFAULT NULL,
  `statusTime` varchar(64) DEFAULT NULL,
  `statusName` varchar(64) DEFAULT NULL,
  `initStatusNumber` varchar(64) DEFAULT NULL,
  `ivrId` varchar(64) DEFAULT NULL,
  `callId` varchar(64) DEFAULT NULL,
  `callEvent` varchar(64) DEFAULT NULL,
  `eventUniqueId` varchar(64) DEFAULT NULL,
  `pushType` varchar(64) DEFAULT NULL,
  `mainChannelName` varchar(64) DEFAULT NULL,
  `channelName` varchar(64) DEFAULT NULL,
  `taskId` varchar(64) DEFAULT NULL,
  `satisfactionStartTime` varchar(64) DEFAULT NULL,
  `agentId` varchar(64) DEFAULT NULL,
  `failureReasonDesc` varchar(64) DEFAULT NULL,
  `recordStartTime` varchar(64) DEFAULT NULL,
  `customerAnswerTime` varchar(64) DEFAULT NULL,
  `satisfactionKeys` varchar(255) DEFAULT NULL,
  `satisfactionType` varchar(64) DEFAULT NULL,
  `agentAnswerTime` varchar(64) DEFAULT NULL,
  `customerNumberCity` varchar(64) DEFAULT NULL,
  `hangupSide` varchar(64) DEFAULT NULL,
  `queueStartTime` varchar(64) DEFAULT NULL,
  `satisfactionDuration` int(11) DEFAULT NULL,
  `satisfactionEndTime` varchar(64) DEFAULT NULL,
  `customerNumberProvince` varchar(64) DEFAULT NULL,
  `bridgeTime` varchar(64) DEFAULT NULL,
  `groupNumber` varchar(64) DEFAULT NULL,
  `agentTelNumber` varchar(64) DEFAULT NULL,
  `failureReason` varchar(64) DEFAULT NULL,
  `refAgentNumber` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`call_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='七陌外呼信息表';

-- ----------------------------
