-- Table structure for guohua_service_dashboard_customer_monthly_snapshot
-- ----------------------------
DROP TABLE IF EXISTS `guohua_service_dashboard_customer_monthly_snapshot`;
CREATE TABLE `guohua_service_dashboard_customer_monthly_snapshot` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `stat_month` char(7) NOT NULL COMMENT '统计月份 YYYY-MM',
  `snapshot_as_of_date` date NOT NULL COMMENT '本批快照统计截止日（通常为昨日/月末）',
  `customer_id` int(11) NOT NULL COMMENT '客户ID guohua_customer.customer_id',
  `service_userid` varchar(64) NOT NULL DEFAULT '' COMMENT '截止日客户归属客服 userid',
  `customer_source` varchar(8) NOT NULL DEFAULT '' COMMENT '有效客户来源：1=FESCO 2=自销 3=机构运营',
  `service_customer_flag` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否进入统一服务客户集合 1是0否',
  `service_customer_reason` varchar(255) NOT NULL DEFAULT '' COMMENT '命中/未命中服务客户口径的说明或代码',
  `active_contract_count` int(11) NOT NULL DEFAULT 0 COMMENT '截止日有效服务合同数',
  `has_direct_contract` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否至少有一份直雇服务合同',
  `has_dispatch_contract` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否至少有一份派遣服务合同',
  `required_person_count` int(11) NOT NULL DEFAULT 0 COMMENT '全部服务合同约定人数汇总（合同事实，非缺编锚点）',
  `onsite_count` int(11) NOT NULL DEFAULT 0 COMMENT '客户在职人数：persons_match.office_status=2（公司考核口径，覆盖FESCO）',
  `light_onsite_count` int(11) NOT NULL DEFAULT 0 COMMENT '轻残在职人数 is_weight_disable=2',
  `weight_onsite_count` int(11) NOT NULL DEFAULT 0 COMMENT '重残在职人数 is_weight_disable=1',
  `gap_person_count` int(11) NOT NULL DEFAULT 0 COMMENT '不落快照恒为0；缺编实时读通知类型8/15，锚点为回款计划人数',
  `crm_active_account_count` int(11) NOT NULL DEFAULT 0 COMMENT '有效CRM企业账号数',
  `mini_active_account_count` int(11) NOT NULL DEFAULT 0 COMMENT '有效小程序客户账号数',
  `active_account_count` int(11) NOT NULL DEFAULT 0 COMMENT '两端有效账号去重/汇总数',
  `account_opened_flag` tinyint(1) NOT NULL DEFAULT 0 COMMENT '至少存在一个有效企业端账号 1是0否',
  `bind_pending_count` int(11) NOT NULL DEFAULT 0 COMMENT '小程序客户绑定待审核数',
  `login_count` int(11) NOT NULL DEFAULT 0 COMMENT '当月助益行登录次数（Mongo market_customer_login_log 按客户当月累计）',
  `login_active_flag` tinyint(1) NOT NULL DEFAULT 0 COMMENT '当月是否至少登录一次助益行 1是0否',
  `last_login_time` datetime DEFAULT NULL COMMENT '截止快照日最近一次助益行登录时间',
  `bill_required_count` int(11) NOT NULL DEFAULT 0 COMMENT '当月应客户确认账单数',
  `bill_confirmed_count` int(11) NOT NULL DEFAULT 0 COMMENT '当月已确认账单数',
  `bill_self_confirmed_count` int(11) NOT NULL DEFAULT 0 COMMENT '当月客户自主确认账单数 source=1',
  `bill_agent_confirmed_count` int(11) NOT NULL DEFAULT 0 COMMENT '当月后台代确认账单数 source=2',
  `bill_unconfirmed_count` int(11) NOT NULL DEFAULT 0 COMMENT '当月未确认账单数',
  `bill_amount` decimal(16,2) NOT NULL DEFAULT 0.00 COMMENT '当月账单收费总额',
  `bill_source_covered_count` int(11) NOT NULL DEFAULT 0 COMMENT '存在有效确认来源流水的账单数',
  `demand_confirm_required_count` int(11) NOT NULL DEFAULT 0 COMMENT '当月应客户确认需求数',
  `demand_self_confirmed_count` int(11) NOT NULL DEFAULT 0 COMMENT '当月客户自主确认需求数 source=1',
  `demand_agent_confirmed_count` int(11) NOT NULL DEFAULT 0 COMMENT '当月后台代确认需求数 source=2',
  `demand_unconfirmed_count` int(11) NOT NULL DEFAULT 0 COMMENT '当月未确认需求数',
  `demand_source_covered_count` int(11) NOT NULL DEFAULT 0 COMMENT '存在有效确认来源流水的需求数',
  `product_confirm_required_count` int(11) NOT NULL DEFAULT 0 COMMENT '当月应客户确认产品订单数',
  `product_self_confirmed_count` int(11) NOT NULL DEFAULT 0 COMMENT '当月客户通过确认链路自主确认订单数',
  `product_agent_confirmed_count` int(11) NOT NULL DEFAULT 0 COMMENT '后台代确认订单数（现阶段无可靠source时保持0并降质量）',
  `product_unconfirmed_count` int(11) NOT NULL DEFAULT 0 COMMENT '当月未确认产品订单数',
  `product_source_covered_count` int(11) NOT NULL DEFAULT 0 COMMENT '确认来源可判定的产品订单数',
  `operation_required_count` int(11) NOT NULL DEFAULT 0 COMMENT '账单+需求+产品订单应确认总数',
  `operation_self_count` int(11) NOT NULL DEFAULT 0 COMMENT '客户自主确认总数',
  `operation_agent_count` int(11) NOT NULL DEFAULT 0 COMMENT '后台代确认总数',
  `operation_unconfirmed_count` int(11) NOT NULL DEFAULT 0 COMMENT '未确认总数',
  `operation_source_covered_count` int(11) NOT NULL DEFAULT 0 COMMENT '确认来源可判定的操作总数',
  `demand_created_count` int(11) NOT NULL DEFAULT 0 COMMENT '当月新增有效需求数',
  `demand_created_person_count` int(11) NOT NULL DEFAULT 0 COMMENT '当月新增需求人数合计（交付率分母）',
  `demand_created_arrived_count` int(11) NOT NULL DEFAULT 0 COMMENT '上述当月新增需求截至截止日实际到岗人数（按demand_id/persons_id去重）',
  `demand_completed_count` int(11) NOT NULL DEFAULT 0 COMMENT '当月完成需求数',
  `demand_finish_days_sum` int(11) NOT NULL DEFAULT 0 COMMENT '当月完成且有finish_time需求的交付天数之和',
  `demand_finish_days_sample_count` int(11) NOT NULL DEFAULT 0 COMMENT '平均交付天数有效样本数',
  `expiring_90d_contract_count` int(11) NOT NULL DEFAULT 0 COMMENT '截止日90天内到期服务合同数',
  `expiring_90d_customer_flag` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否存在90天内到期服务合同',
  `expired_in_month_contract_count` int(11) NOT NULL DEFAULT 0 COMMENT '当月到期服务合同数',
  `renewed_contract_count` int(11) NOT NULL DEFAULT 0 COMMENT '当月到期且存在有效后继合同的合同数',
  `renewed_customer_flag` tinyint(1) NOT NULL DEFAULT 0 COMMENT '当月到期客户是否至少命中一次续签',
  `nearest_contract_end_date` date DEFAULT NULL COMMENT '最近一份服务合同到期日',
  `dispatch_wages_count` int(11) NOT NULL DEFAULT 0 COMMENT '当月有效派遣发薪申请数',
  `borrow_period_count` int(11) NOT NULL DEFAULT 0 COMMENT '当月发生垫付期数',
  `borrow_unpaid_period_count` int(11) NOT NULL DEFAULT 0 COMMENT '截至截止日仍未回款垫付期数',
  `borrow_abnormal_period_count` int(11) NOT NULL DEFAULT 0 COMMENT '未获白名单审批的异常垫付期数',
  `borrow_whitelist_period_count` int(11) NOT NULL DEFAULT 0 COMMENT '已获审批的正常垫付期数',
  `borrow_unpaid_amount` decimal(16,2) NOT NULL DEFAULT 0.00 COMMENT '截至截止日垫付未回款金额',
  `continuous_borrow_months` int(11) NOT NULL DEFAULT 0 COMMENT '截至本月连续垫付未回款月数',
  `borrow_outstanding_period_count` int(11) NOT NULL DEFAULT 0 COMMENT '截至快照日累计垫付未回款期数',
  `borrow_outstanding_amount` decimal(16,2) NOT NULL DEFAULT 0.00 COMMENT '截至快照日累计垫付未回款本金口径金额',
  `labor_product_order_count` int(11) NOT NULL DEFAULT 0 COMMENT '统计周期内有效劳动产品订单数',
  `labor_product_completed_order_count` int(11) NOT NULL DEFAULT 0 COMMENT '统计周期内已完成劳动产品订单数 order_status=5',
  `labor_product_completed_amount` decimal(16,2) NOT NULL DEFAULT 0.00 COMMENT '已完成劳动产品订单金额',
  `activity_signed_count` int(11) NOT NULL DEFAULT 0 COMMENT '统计周期内客户有效签到活动场次',
  `activity_sign_person_count` int(11) NOT NULL DEFAULT 0 COMMENT '统计周期内活动签到人数',
  `product_loop_flag` tinyint(1) NOT NULL DEFAULT 0 COMMENT '劳动产品闭环 1是0否',
  `activity_loop_flag` tinyint(1) NOT NULL DEFAULT 0 COMMENT '关爱活动闭环 1是0否',
  `report_required_count` int(11) NOT NULL DEFAULT 0 COMMENT '当月应生成月报数，通常服务客户为1',
  `report_success_count` int(11) NOT NULL DEFAULT 0 COMMENT '当月成功生成月报数',
  `report_failed_count` int(11) NOT NULL DEFAULT 0 COMMENT '当月生成失败月报数',
  `report_file_count` int(11) NOT NULL DEFAULT 0 COMMENT '当月有效月报文件数',
  `todo_notice_count` int(11) NOT NULL DEFAULT 0 COMMENT '不落快照恒为0；待办实时读guohua_notice_summary（CRM每日05:00快照，按user_id派发）',
  `warning_count` int(11) NOT NULL DEFAULT 0 COMMENT '看板规则计算出的客户预警项数（基于本表已落字段，不含待办/缺编）',
  `snapshot_status` tinyint(1) NOT NULL DEFAULT 0 COMMENT '0计算中1有效2已封存3失败',
  `is_finalized` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否封存 1是0否',
  `data_version` int(11) NOT NULL DEFAULT 1 COMMENT '指标口径版本',
  `snapshot_batch_no` varchar(64) NOT NULL DEFAULT '' COMMENT '整月计算批次号；客户/合同两表必须一致',
  `calc_start_time` datetime DEFAULT NULL COMMENT '批次开始计算时间',
  `calc_end_time` datetime DEFAULT NULL COMMENT '批次计算完成时间',
  `error_message` varchar(500) NOT NULL DEFAULT '' COMMENT '该行/批次最近错误信息',
  `quality_flags` text DEFAULT NULL COMMENT '数据覆盖/缺失/口径降级标记JSON',
  `add_time` datetime NOT NULL DEFAULT current_timestamp() COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp() COMMENT '更新时间',
  `is_delete` tinyint(1) NOT NULL DEFAULT 1 COMMENT '1有效0删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_service_customer_month` (`stat_month`,`customer_id`),
  KEY `idx_service_customer_month_service` (`stat_month`,`service_userid`,`service_customer_flag`),
  KEY `idx_service_customer_month_source` (`stat_month`,`customer_source`,`service_customer_flag`),
  KEY `idx_service_customer_customer_month` (`customer_id`,`stat_month`),
  KEY `idx_service_customer_month_status` (`stat_month`,`snapshot_status`,`is_finalized`),
  KEY `idx_service_customer_batch` (`snapshot_batch_no`)
) ENGINE=InnoDB AUTO_INCREMENT=40502 DEFAULT CHARSET=utf8mb4 COMMENT='客服看板客户月度快照：一月一客户';

-- ----------------------------
