-- Table structure for guohua_payment_confirm
-- ----------------------------
DROP TABLE IF EXISTS `guohua_payment_confirm`;
CREATE TABLE `guohua_payment_confirm` (
  `payment_confirm_id` int(11) NOT NULL AUTO_INCREMENT COMMENT '确认id',
  `confirm_status` tinyint(4) NOT NULL COMMENT '确认状态 0 未确认 1已确认',
  `payment_id` int(11) NOT NULL DEFAULT 0 COMMENT '未确认回款id',
  `company_name` varchar(255) NOT NULL DEFAULT '' COMMENT '到款客户',
  `receivable_amount` decimal(11,2) NOT NULL DEFAULT 0.00 COMMENT '应收金额',
  `open_amount` decimal(11,2) NOT NULL COMMENT '开票金额',
  `confirm_cp_amount` decimal(11,2) NOT NULL DEFAULT 0.00 COMMENT '确认代收代付金额',
  `confirm_amount` decimal(11,2) NOT NULL COMMENT '确认到款金额',
  `confirm_product_amount` decimal(11,2) DEFAULT 0.00 COMMENT '确认劳动产品金额',
  `confirm_fusion_activity_fees` decimal(11,2) NOT NULL DEFAULT 0.00 COMMENT '已确认融合活动费用',
  `service_charge` decimal(11,2) NOT NULL DEFAULT 0.00 COMMENT '服务费',
  `abstract` varchar(255) NOT NULL COMMENT '摘要',
  `account_id` int(11) NOT NULL COMMENT '收款账户id',
  `department_id` varchar(255) NOT NULL DEFAULT '0' COMMENT '子部门id',
  `main_department_id` int(11) NOT NULL DEFAULT 0 COMMENT '主部门id',
  `service_line_id` int(11) NOT NULL COMMENT '业务线id',
  `store_id` varchar(255) NOT NULL DEFAULT '0' COMMENT '单店id',
  `product_id` int(11) NOT NULL DEFAULT 0 COMMENT '产品id',
  `project_id` int(11) NOT NULL DEFAULT 0 COMMENT '项目id',
  `remarks` varchar(500) NOT NULL DEFAULT '' COMMENT '备注',
  `payment_date` date DEFAULT NULL COMMENT '回款日期',
  `add_userid` varchar(255) NOT NULL DEFAULT '' COMMENT '添加人id',
  `add_time` datetime NOT NULL DEFAULT current_timestamp() COMMENT '添加时间',
  `confirm_userid` varchar(255) NOT NULL DEFAULT '' COMMENT '确认人id',
  `confirm_time` datetime DEFAULT NULL COMMENT '确认时间',
  `is_delete` tinyint(4) NOT NULL DEFAULT 1 COMMENT '是否删除 1未删除 0已删除',
  `product_data` varchar(255) NOT NULL DEFAULT '' COMMENT '产品多级id 前端反显使用',
  `bill_id` int(11) NOT NULL DEFAULT 0 COMMENT '账单开票id',
  `confirm_type` tinyint(4) NOT NULL DEFAULT 1 COMMENT '确认类型 1回款未确认 2账单开票',
  `contract_id` int(11) DEFAULT NULL COMMENT '合同id',
  `payment_plan_id` varchar(255) DEFAULT NULL COMMENT '合同回款计划id',
  `salary_id` int(11) DEFAULT NULL COMMENT '薪资账单id',
  `pay_company_name` varchar(255) DEFAULT NULL COMMENT '实际归属客户',
  `dispatch_payment_plan_id` varchar(255) DEFAULT NULL COMMENT '派遣回款计划id',
  `sign_type` int(11) DEFAULT NULL COMMENT '1 新签到款 2续签到款',
  `sign_amount_type` int(11) DEFAULT NULL COMMENT '1 新签回款提成 2续签回款新签提成  3续签回款提成',
  `company_name_norm` varchar(255) GENERATED ALWAYS AS (trim(regexp_replace(`company_name`,'[^[:alnum:]\\x{4e00}-\\x{9fa5}]',''))) STORED,
  `customer_id` int(11) DEFAULT NULL COMMENT '客户ID',
  `bill_detail_id` int(11) NOT NULL DEFAULT 0 COMMENT '关联开票明细id',
  `bill_detail_amount` decimal(11,2) NOT NULL DEFAULT 0.00 COMMENT '开票明细分摊金额',
  PRIMARY KEY (`payment_confirm_id`) USING BTREE,
  KEY `index_company_name` (`company_name`) USING BTREE,
  KEY `index_payment_id` (`payment_id`) USING BTREE,
  KEY `index_contract_id` (`contract_id`) USING BTREE,
  KEY `idx_payment_confirm_status_delete_time` (`confirm_status`,`is_delete`,`confirm_time`,`payment_date`),
  KEY `idx_payment_confirm_company` (`company_name`,`confirm_status`,`is_delete`),
  KEY `idx_payment_confirm_status_delete_time_order` (`confirm_status`,`is_delete`,`confirm_time`,`payment_date`,`payment_confirm_id`),
  KEY `idx_payment_confirm_delete_plan` (`is_delete`,`payment_plan_id`),
  KEY `idx_company_norm_status_delete` (`company_name_norm`,`confirm_status`,`is_delete`)
) ENGINE=InnoDB AUTO_INCREMENT=19720 DEFAULT CHARSET=utf8mb4 COMMENT='回款已确认表&应收款表';

-- ----------------------------
