-- Table structure for guohua_call_center_moor
-- ----------------------------
DROP TABLE IF EXISTS `guohua_call_center_moor`;
CREATE TABLE `guohua_call_center_moor` (
  `call_id` varchar(64) NOT NULL COMMENT '呼叫id',
  `customer_id` int(11) DEFAULT NULL COMMENT '客户id',
  `add_userid` varchar(64) DEFAULT NULL COMMENT '人员id',
  `add_time` datetime DEFAULT current_timestamp() COMMENT '添加时间',
  `update_time` datetime DEFAULT current_timestamp() COMMENT '更新时间',
  `FromExten` varchar(64) DEFAULT NULL COMMENT '坐席工号',
  `CallNo` varchar(64) DEFAULT NULL COMMENT '主叫号码',
  `CalledNo` varchar(64) DEFAULT NULL COMMENT '被叫号码',
  `CallSheetID` varchar(64) DEFAULT NULL COMMENT '通话记录ID,CallSheetID 是这条通话记录再DB中的唯一id',
  `CallID` varchar(64) DEFAULT NULL COMMENT '通话ID,通话连接的在系统中的唯一标识。CallID 是在通话进行中channel的id,可以用这个id来挂断通话之类的操作。一个channel有一个CallID,但一个call可能会出现在多个通话中,比如呼入转接。',
  `CallType` varchar(64) DEFAULT NULL COMMENT '通话类型：dialout外呼通话,normal普通来电,transfer呼入转接,dialTransfer外呼转接',
  `Ring` varchar(64) DEFAULT NULL COMMENT '通话振铃时间（话务进入呼叫中心系统的时间）',
  `RingingDate` varchar(64) DEFAULT NULL COMMENT '被叫振铃开始时间（呼入是按座席振铃的时间,外呼按用户振铃的时间）',
  `Begin` varchar(64) DEFAULT NULL COMMENT '通话接通时间（双方开始通话的时间,如果被叫没接听的话为空）',
  `End` varchar(64) DEFAULT NULL COMMENT '通话结束时间',
  `QueueTime` varchar(64) DEFAULT NULL COMMENT '来电进入技能组时间',
  `Exten` varchar(64) DEFAULT NULL COMMENT '处理坐席的工号,历史原因该字段与Agent相同',
  `Agent` varchar(255) DEFAULT NULL,
  `AgentName` varchar(64) DEFAULT NULL COMMENT '处理坐席的姓名',
  `Queue` varchar(64) DEFAULT NULL COMMENT '通话进入的技能组名称',
  `State` varchar(64) DEFAULT NULL COMMENT '接听状态：dealing（已接）,notDeal（振铃未接听）,leak（ivr放弃）,queueLeak（排队放弃）,blackList（黑名单）,voicemail（留言）,limit（并发限制）,failed（失败）\n注意：只有dealing和voicemail状态的通话有录音，其他状态的通话录音地址不可用',
  `RT_UUID` varchar(255) DEFAULT NULL,
  `CallStatus` varchar(255) DEFAULT NULL,
  `CallState` varchar(64) DEFAULT NULL COMMENT '事件状态：Ring, Ringing, Link, Hangup(Unlink也当成Hangup处理)',
  `RealState` varchar(255) DEFAULT NULL,
  `ActionID` varchar(128) DEFAULT NULL COMMENT '通过调用外呼接口时,该字段会保存请求的actionID,其它情况下该字段为空',
  `WebcallActionID` varchar(64) DEFAULT NULL COMMENT '通过调用webcall接口,该字段会保存请求的actionID,其它情况下该字段为空',
  `RecordFile` varchar(255) DEFAULT NULL COMMENT '通话录音文件名：用户要访问录音时,在该文件名前面加上服务器路径即可,如：FileServer/RecordFile',
  `ConsultRecordFiles` varchar(255) DEFAULT NULL,
  `CONSULT_INFOS` varchar(255) DEFAULT NULL,
  `TransferReason` varchar(255) DEFAULT NULL,
  `FileServer` varchar(255) DEFAULT NULL COMMENT '通过FileServer中指定的地址加上RecordFile的值可以获取录音(建议字段长度内容设置为100个字符)',
  `Province` varchar(64) DEFAULT NULL COMMENT '目标号码的省,例如北京市。呼入为来电号码,呼出为去电号码',
  `District` varchar(64) DEFAULT NULL COMMENT '目标号码的市,例如北京市。呼入为来电号码,呼出为去电号码',
  `DistrictCode` varchar(64) DEFAULT NULL,
  `IVRKEY` varchar(64) DEFAULT NULL COMMENT '通话在系统中选择的按键菜单,10004@0。格式为：按键菜单的节点编号@选择的菜单按键。如果为多级菜单则为：10004@0-10005@1。',
  `AccountId` varchar(64) DEFAULT NULL COMMENT '账户编号字段,默认不推送有需求的用户对接时联系七陌技术支持人员进行开通',
  `AccountName` varchar(255) DEFAULT NULL COMMENT '账户名称字段,默认不推送有需求的用户对接时联系七陌技术支持人员进行开通',
  `CdrVar` varchar(255) DEFAULT NULL COMMENT '软电话条中的自定义参数，只有在软电话条中用CdrVar自定义id后才会有该字段。',
  `DialoutStrVar` varchar(255) DEFAULT NULL COMMENT '外呼接口和小号外呼接口中的自定义参数，只有在这两个接口中使用DialoutStrVar参数才会有该字段。',
  `HangupPart` varchar(255) DEFAULT NULL COMMENT '挂机方，字段值解释 ：agent 坐席挂机， customer 用户挂机，system 系统挂机',
  `RealCalled` varchar(255) DEFAULT NULL COMMENT '如果使用的是小号接口外呼或者CallCenter小号模式外呼，这里存放的是真实被叫，CalledNo存放的是小号。',
  `MonitorFilename` varchar(255) DEFAULT NULL COMMENT '录音文件地址，只有 State = dealing 时才有该字段',
  `Account` varchar(255) DEFAULT NULL COMMENT '账户编号字段',
  `RingingTimestamp` varchar(255) DEFAULT NULL COMMENT '被叫振铃开始时间时间戳',
  `is_delete` tinyint(4) DEFAULT 1 COMMENT '是否删除 1否 0是',
  PRIMARY KEY (`call_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='七陌外呼信息表';

-- ----------------------------
