-- Table structure for guohua_customer
-- ----------------------------
DROP TABLE IF EXISTS `guohua_customer`;
CREATE TABLE `guohua_customer` (
  `customer_id` int(11) NOT NULL AUTO_INCREMENT COMMENT '客户ID',
  `customer_parent_id` int(11) DEFAULT NULL COMMENT '父级客户ID',
  `customer_group_id` varchar(255) DEFAULT NULL COMMENT '所属集团ID',
  `is_group_number` int(11) DEFAULT NULL COMMENT '是否为集团号',
  `customer_code` varchar(255) DEFAULT NULL COMMENT '客户编码 如：C20220115014',
  `customer_main_code` varchar(64) DEFAULT NULL COMMENT '客户主体编码：国华:100 杭州:101',
  `customer_name` varchar(255) DEFAULT NULL COMMENT '客户名称',
  `customer_en_shortname` varchar(255) DEFAULT NULL COMMENT '客户英文简称',
  `customer_cn_shortname` varchar(255) DEFAULT NULL COMMENT '客户中文简称',
  `customer_shortcode` varchar(255) DEFAULT NULL COMMENT '客户简码',
  `customer_source` varchar(64) DEFAULT NULL COMMENT '客户来源  1:FESCO  2:自销',
  `customer_address_code` int(11) DEFAULT NULL COMMENT '客户省市区县ID',
  `customer_address_info` varchar(500) DEFAULT NULL COMMENT '客户详细地址',
  `customer_account_bank` varchar(255) DEFAULT NULL COMMENT '客户开户银行',
  `customer_bank_number` varchar(255) DEFAULT NULL COMMENT '客户银行账号',
  `customer_registration_address` varchar(255) DEFAULT NULL COMMENT '客户注册地址',
  `customer_nature_id` int(11) DEFAULT NULL COMMENT '单位性质ID',
  `customer_industry_id` int(11) DEFAULT NULL COMMENT '所属行业ID',
  `customer_registration_area_id` int(11) DEFAULT NULL COMMENT '客户注册地区域ID',
  `customer_tax_place_area_id` int(11) DEFAULT NULL COMMENT '客户报税地区域ID',
  `customer_social_security_area_id` int(11) DEFAULT NULL COMMENT '客户社保所在地区ID',
  `customer_contact_id` int(11) DEFAULT NULL COMMENT '客户首要联系人ID',
  `customer_social_security_id` int(11) DEFAULT NULL COMMENT '客户社保信息ID',
  `customer_salary_id` int(11) DEFAULT NULL COMMENT '客户财务信息ID',
  `customer_tin_code` varchar(255) DEFAULT NULL COMMENT '纳税人识别号',
  `add_userid` varchar(64) DEFAULT NULL COMMENT '添加人ID',
  `add_time` datetime DEFAULT current_timestamp() COMMENT '添加时间',
  `update_userid` varchar(64) DEFAULT NULL COMMENT '更新人ID',
  `update_time` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp() COMMENT '更新时间',
  `service_line_id` int(11) DEFAULT 1 COMMENT '业务线ID',
  `main_department_id` int(11) DEFAULT NULL COMMENT '主部门ID',
  `department_id` int(11) DEFAULT NULL COMMENT '子部门ID',
  `customer_account_phone` varchar(255) DEFAULT NULL COMMENT '客户开户行电话',
  `tmp_id` varchar(255) DEFAULT NULL COMMENT '临时id',
  `min_money_times` decimal(3,2) DEFAULT 1.00 COMMENT '发放最低工资标准倍数',
  `is_prospect` varchar(64) DEFAULT NULL COMMENT '1公海客户 2私海客户',
  `prospect_level` varchar(64) DEFAULT NULL COMMENT '潜在客户级别 S已合作 A高意向 B 中意向  C低意向  D无意向',
  `prospect_source` varchar(64) DEFAULT NULL COMMENT '潜在客户来源  1自拓客户 2渠道客户 3客户转介绍 4网站线索 5广告线索 6活动线索 7展会线索',
  `customer_size` varchar(64) DEFAULT NULL COMMENT '客户规模',
  `competing_id` varchar(64) DEFAULT NULL COMMENT '竞品id',
  `competing_name` varchar(64) DEFAULT NULL COMMENT '竞品名称',
  `product_id` varchar(64) DEFAULT NULL COMMENT '产品类型',
  `wechat` varchar(64) DEFAULT NULL COMMENT '微信号',
  `money_avg_year` int(11) DEFAULT NULL COMMENT '年平均工资',
  `follow_date` varchar(255) DEFAULT NULL COMMENT '最近跟进日期',
  `product_expire` varchar(255) DEFAULT NULL COMMENT '竞品到期日期',
  `return_reason` varchar(255) DEFAULT NULL COMMENT '退回原因',
  `return_time` datetime DEFAULT NULL COMMENT '退回时间',
  `responsible_userid` varchar(64) DEFAULT NULL COMMENT '负责人',
  `tenure_time` varchar(64) DEFAULT NULL COMMENT '剩余保有时间',
  `high_seas` varchar(255) DEFAULT NULL COMMENT '公海名',
  `customer_type` varchar(64) DEFAULT NULL COMMENT '客户类型 1客户 2渠道',
  `web_url` varchar(255) DEFAULT NULL COMMENT '客户网址',
  `cooperate_attribute` varchar(255) DEFAULT NULL COMMENT '合作类型  1直雇 2派遣',
  `remarks` varchar(255) DEFAULT NULL COMMENT '备注',
  `contract_sum` int(11) DEFAULT NULL COMMENT '合同数',
  `channel_id` varchar(64) DEFAULT NULL COMMENT '渠道id',
  `channel_price` int(11) DEFAULT 0 COMMENT '渠道单价',
  `is_disabled_money` tinyint(4) DEFAULT 2 COMMENT '是否在缴纳残保金 1是 2否',
  `disabled_money` int(11) DEFAULT 0 COMMENT '当前缴纳残保金金额',
  `staff_number` varchar(64) DEFAULT '0' COMMENT '企业现有员工数量',
  `cooperation_date` varchar(64) DEFAULT NULL COMMENT '合作日期',
  `cooperation_end_date` varchar(64) DEFAULT NULL COMMENT '合作终止日期',
  `customer_status` tinyint(4) DEFAULT NULL COMMENT '客户状态 1潜在客户 2成交客户 3无意向 4终止合作',
  `is_delete` tinyint(4) DEFAULT 1 COMMENT '是否删除 1未删除 0已删除',
  `is_customer_clue` tinyint(4) DEFAULT 0 COMMENT '是否线索客户 1是 0否 ',
  `claim_time` datetime DEFAULT current_timestamp() COMMENT '认领时间',
  `is_clue_share` tinyint(4) DEFAULT 0 COMMENT '是否已分配',
  `clue_id` int(11) DEFAULT NULL COMMENT '线索id',
  `brand_id` int(11) DEFAULT NULL COMMENT '品牌id',
  `service_userid` varchar(32) DEFAULT NULL COMMENT '内部服务人员',
  `service_department_id` int(11) DEFAULT NULL COMMENT '外企服务部门id',
  `declare_status` varchar(32) DEFAULT '0' COMMENT '申报状态  0未申报 1申报中  2已完成',
  `contact_id` tinyint(4) DEFAULT 0 COMMENT '是否线索客户',
  `service_share_status` varchar(32) DEFAULT '0' COMMENT '客服分配状态 0未分配  1待分配  2已分配',
  `wanda_area_id` int(11) DEFAULT NULL COMMENT '万达区域id',
  `top_customer` varchar(32) DEFAULT '0' COMMENT '是否20大客户 1是 0否',
  `customer_contract_sn` varchar(255) DEFAULT NULL COMMENT '客户协议编号',
  `is_channel_customer` tinyint(4) DEFAULT NULL COMMENT '1客户为渠道介绍  2客户为渠道本身',
  `last_follow_time` datetime DEFAULT NULL COMMENT '最近跟进时间',
  `cooperation_end_reason` varchar(1000) DEFAULT NULL COMMENT '客户终止原因',
  `channel_rebate_ratio` float(11,2) DEFAULT NULL COMMENT '渠道返款比例 正常0% 15% 30% 35% 40% 其他',
  `customer_name_norm` varchar(255) GENERATED ALWAYS AS (trim(regexp_replace(`customer_name`,'[^[:alnum:]\\x{4e00}-\\x{9fa5}]',''))) STORED,
  `service_level` tinyint(1) DEFAULT NULL COMMENT '服务等级：1普通 2标杆 3战略',
  PRIMARY KEY (`customer_id`) USING BTREE,
  KEY `customer_address_code` (`customer_address_code`) USING BTREE,
  KEY `index_is_delete` (`is_delete`) USING BTREE,
  KEY `index_customer_name` (`customer_name`) USING BTREE,
  KEY `idx_resp_userid` (`responsible_userid`) USING BTREE,
  KEY `customer_group_id` (`customer_group_id`) USING BTREE,
  KEY `_index_customer_id` (`customer_id`) USING BTREE,
  KEY `_index_clue_id` (`clue_id`) USING BTREE,
  KEY `idx_customer_delete` (`is_delete`,`customer_id`),
  KEY `idx_customer_name_delete_responsible_service` (`customer_name`,`is_delete`,`responsible_userid`,`service_userid`),
  KEY `idx_customer_norm_delete` (`customer_name_norm`,`is_delete`)
) ENGINE=InnoDB AUTO_INCREMENT=670346 DEFAULT CHARSET=utf8mb4 COMMENT='客户信息表';

-- ----------------------------
