-- Table structure for guohua_MBGC_disabled_dispatch_fee_detail
-- ----------------------------
DROP TABLE IF EXISTS `guohua_MBGC_disabled_dispatch_fee_detail`;
CREATE TABLE `guohua_MBGC_disabled_dispatch_fee_detail` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `source_file` varchar(255) DEFAULT NULL COMMENT '来源文件',
  `source_sheet` varchar(50) DEFAULT '收费明细' COMMENT '来源sheet',
  `source_row` int(11) DEFAULT NULL COMMENT 'Excel原始行号',
  `serial_no` int(11) DEFAULT NULL COMMENT '序号',
  `company_short_name` varchar(20) DEFAULT NULL COMMENT '公司简称',
  `year` int(11) DEFAULT NULL COMMENT '年度',
  `month_label` varchar(50) DEFAULT NULL COMMENT '月份',
  `period_date` date DEFAULT NULL COMMENT '标准月份日期',
  `employee_salary_total_102` decimal(18,6) DEFAULT NULL COMMENT '102表：从业人员工资总额',
  `person_name` varchar(50) DEFAULT NULL COMMENT '姓名',
  `id_number` varchar(30) DEFAULT NULL COMMENT '身份证号',
  `gender` varchar(10) DEFAULT NULL COMMENT '性别',
  `unique_no` varchar(32) DEFAULT NULL COMMENT '唯一号',
  `department` varchar(100) DEFAULT NULL COMMENT '部门',
  `pension_unemployment_base` decimal(18,6) DEFAULT NULL COMMENT '养老失业基数',
  `medical_base` decimal(18,6) DEFAULT NULL COMMENT '医疗基数',
  `injury_base` decimal(18,6) DEFAULT NULL COMMENT '工伤基数',
  `housing_fund_base` decimal(18,6) DEFAULT NULL COMMENT '公积金基数',
  `company_pension_amount` decimal(18,6) DEFAULT NULL COMMENT '企业养老部分 16%',
  `company_unemployment_amount` decimal(18,6) DEFAULT NULL COMMENT '企业失业部分 0.8%',
  `company_medical_amount` decimal(18,6) DEFAULT NULL COMMENT '企业医疗保险 9.8%',
  `company_injury_amount` decimal(18,6) DEFAULT NULL COMMENT '企业工伤部分 0.36%',
  `company_housing_fund_amount` decimal(18,6) DEFAULT NULL COMMENT '企业住房公积金 12%',
  `company_social_fund_total` decimal(18,6) DEFAULT NULL COMMENT '公司社保公积金合计',
  `person_pension_amount` decimal(18,6) DEFAULT NULL COMMENT '个人养老部分 8%',
  `person_unemployment_amount` decimal(18,6) DEFAULT NULL COMMENT '个人失业部分 0.5%',
  `person_medical_amount` decimal(18,6) DEFAULT NULL COMMENT '个人医疗部分 2%+3',
  `person_housing_fund_amount` decimal(18,6) DEFAULT NULL COMMENT '个人住房公积金 12%',
  `person_social_fund_total` decimal(18,6) DEFAULT NULL COMMENT '个人社保公积金合计',
  `net_salary` decimal(18,6) DEFAULT NULL COMMENT '员工税后实发',
  `fesco_payment_total` decimal(18,6) DEFAULT NULL COMMENT '支付FESCO合计（代收代付项 人/月）',
  `service_fee` decimal(18,6) DEFAULT NULL COMMENT '服务费',
  `total_amount` decimal(18,6) DEFAULT NULL COMMENT 'Total',
  `created_at` datetime DEFAULT current_timestamp() COMMENT '创建时间',
  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp() COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_company_period` (`company_short_name`,`year`,`month_label`),
  KEY `idx_id_number` (`id_number`),
  KEY `idx_unique_no` (`unique_no`),
  KEY `idx_period_date` (`period_date`),
  KEY `idx_source_row` (`source_row`)
) ENGINE=InnoDB AUTO_INCREMENT=2639 DEFAULT CHARSET=utf8mb4 COMMENT='残疾派遣费用收费明细表';

-- ----------------------------
