-- Table structure for guohua_service_dashboard_contract_monthly_snapshot
-- ----------------------------
DROP TABLE IF EXISTS `guohua_service_dashboard_contract_monthly_snapshot`;
CREATE TABLE `guohua_service_dashboard_contract_monthly_snapshot` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `stat_month` char(7) NOT NULL COMMENT '统计月份 YYYY-MM',
  `snapshot_as_of_date` date NOT NULL COMMENT '本批快照统计截止日',
  `contract_id` bigint(20) NOT NULL COMMENT '合同ID guohua_contract.contract_id',
  `customer_id` int(11) NOT NULL COMMENT '客户ID guohua_customer.customer_id',
  `service_userid` varchar(64) NOT NULL DEFAULT '' COMMENT '截止日客户归属客服 userid',
  `customer_source` varchar(8) NOT NULL DEFAULT '' COMMENT '有效客户来源',
  `contract_attribute` varchar(8) NOT NULL DEFAULT '' COMMENT '合同属性 1=直雇2=派遣',
  `contract_status_id` int(11) NOT NULL DEFAULT 0 COMMENT '合同状态ID',
  `sp_status` varchar(16) NOT NULL DEFAULT '' COMMENT '合同审批状态',
  `contract_service_flag` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否为统一服务客户集合中的有效服务合同',
  `contract_start_date` date DEFAULT NULL COMMENT '合同开始日期',
  `contract_end_date` date DEFAULT NULL COMMENT '合同结束日期',
  `payment_method` varchar(32) NOT NULL DEFAULT '' COMMENT '回款方式 guohua_contract.payment_method',
  `weight_price` decimal(10,2) NOT NULL DEFAULT 0.00 COMMENT '重残报价/人 guohua_contract.weight_price',
  `light_price` decimal(10,2) NOT NULL DEFAULT 0.00 COMMENT '轻残报价/人 guohua_contract.light_price',
  `contract_money` decimal(12,2) NOT NULL DEFAULT 0.00 COMMENT '合同总金额 guohua_contract.contract_money',
  `required_light_count` int(11) NOT NULL DEFAULT 0 COMMENT '合同约定轻残人数',
  `required_weight_count` int(11) NOT NULL DEFAULT 0 COMMENT '合同约定重残人数',
  `required_person_count` int(11) NOT NULL DEFAULT 0 COMMENT '合同应配总人数',
  `onsite_light_count` int(11) NOT NULL DEFAULT 0 COMMENT '合同轻残在职：rel_contract_persons_total.light_num（合同履约口径）',
  `onsite_weight_count` int(11) NOT NULL DEFAULT 0 COMMENT '合同重残在职：rel_contract_persons_total.weight_num',
  `onsite_count` int(11) NOT NULL DEFAULT 0 COMMENT '合同在职：light_num+weight_num（合同月快照，取当月最新add_time行）',
  `gap_person_count` int(11) NOT NULL DEFAULT 0 COMMENT '不落快照恒为0；缺编实时读通知类型8/15',
  `expiring_90d_flag` tinyint(1) NOT NULL DEFAULT 0 COMMENT '截止日90天内到期 1是0否',
  `expired_in_month_flag` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否在统计月到期',
  `renewed_flag` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否存在审批通过且结束日晚于本合同的后继合同',
  `renewal_contract_id` bigint(20) DEFAULT NULL COMMENT '命中的后继合同ID',
  `renewal_contract_end_date` date DEFAULT NULL COMMENT '后继合同结束日期',
  `bill_required_count` int(11) NOT NULL DEFAULT 0 COMMENT '合同当月应确认账单数',
  `bill_confirmed_count` int(11) NOT NULL DEFAULT 0 COMMENT '合同当月已确认账单数',
  `bill_self_confirmed_count` int(11) NOT NULL DEFAULT 0 COMMENT '合同当月客户自主确认账单数',
  `bill_agent_confirmed_count` int(11) NOT NULL DEFAULT 0 COMMENT '合同当月后台代确认账单数',
  `bill_unconfirmed_count` int(11) NOT NULL DEFAULT 0 COMMENT '合同当月未确认账单数',
  `bill_amount` decimal(16,2) NOT NULL DEFAULT 0.00 COMMENT '合同当月账单收费总额',
  `demand_created_count` int(11) NOT NULL DEFAULT 0 COMMENT '合同当月新增有效需求数',
  `demand_created_person_count` int(11) NOT NULL DEFAULT 0 COMMENT '合同当月新增需求人数',
  `demand_created_arrived_count` int(11) NOT NULL DEFAULT 0 COMMENT '上述需求截至截止日实际到岗人数',
  `demand_completed_count` int(11) NOT NULL DEFAULT 0 COMMENT '合同当月完成需求数',
  `demand_finish_days_sum` int(11) NOT NULL DEFAULT 0 COMMENT '完成且有finish_time需求的交付天数之和',
  `demand_finish_days_sample_count` int(11) NOT NULL DEFAULT 0 COMMENT '平均交付天数有效样本数',
  `dispatch_wages_count` int(11) NOT NULL DEFAULT 0 COMMENT '合同当月有效派遣发薪申请数',
  `borrow_period_count` int(11) NOT NULL DEFAULT 0 COMMENT '合同当月发生垫付期数',
  `borrow_unpaid_period_count` int(11) NOT NULL DEFAULT 0 COMMENT '截至截止日仍未回款垫付期数',
  `borrow_unpaid_amount` decimal(16,2) NOT NULL DEFAULT 0.00 COMMENT '截至截止日合同垫付未回款金额',
  `labor_product_order_count` int(11) NOT NULL DEFAULT 0 COMMENT '合同统计周期内有效劳动产品订单数',
  `labor_product_completed_order_count` int(11) NOT NULL DEFAULT 0 COMMENT '合同统计周期内已完成订单数',
  `labor_product_standard_order_count` int(11) NOT NULL DEFAULT 0 COMMENT '标准预算订单数 budget_type=1',
  `labor_product_extra_order_count` int(11) NOT NULL DEFAULT 0 COMMENT '额外预算订单数 budget_type=2',
  `labor_product_completed_amount` decimal(16,2) NOT NULL DEFAULT 0.00 COMMENT '合同已完成劳动产品订单金额',
  `snapshot_status` tinyint(1) NOT NULL DEFAULT 0 COMMENT '0计算中1有效2已封存3失败',
  `is_finalized` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否封存 1是0否',
  `data_version` int(11) NOT NULL DEFAULT 1 COMMENT '指标口径版本',
  `snapshot_batch_no` varchar(64) NOT NULL DEFAULT '' COMMENT '整月计算批次号；客户/合同两表必须一致',
  `calc_start_time` datetime DEFAULT NULL COMMENT '批次开始计算时间',
  `calc_end_time` datetime DEFAULT NULL COMMENT '批次计算完成时间',
  `error_message` varchar(500) NOT NULL DEFAULT '' COMMENT '该行/批次最近错误信息',
  `quality_flags` text DEFAULT NULL COMMENT '数据覆盖/缺失/口径降级标记JSON',
  `add_time` datetime NOT NULL DEFAULT current_timestamp() COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp() COMMENT '更新时间',
  `is_delete` tinyint(1) NOT NULL DEFAULT 1 COMMENT '1有效0删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_service_contract_month` (`stat_month`,`contract_id`),
  KEY `idx_service_contract_month_customer` (`stat_month`,`customer_id`,`contract_service_flag`),
  KEY `idx_service_contract_month_service` (`stat_month`,`service_userid`,`contract_service_flag`),
  KEY `idx_service_contract_month_attr` (`stat_month`,`contract_attribute`,`contract_service_flag`),
  KEY `idx_service_contract_customer_month` (`customer_id`,`stat_month`),
  KEY `idx_service_contract_contract_month` (`contract_id`,`stat_month`),
  KEY `idx_service_contract_month_status` (`stat_month`,`snapshot_status`,`is_finalized`),
  KEY `idx_service_contract_batch` (`snapshot_batch_no`)
) ENGINE=InnoDB AUTO_INCREMENT=46072 DEFAULT CHARSET=utf8mb4 COMMENT='客服看板合同月度快照：一月一合同';

-- ----------------------------
