-- Table structure for guohua_expend
-- ----------------------------
DROP TABLE IF EXISTS `guohua_expend`;
CREATE TABLE `guohua_expend` (
  `expend_id` int(11) NOT NULL AUTO_INCREMENT,
  `budget_department_id` varchar(255) DEFAULT NULL COMMENT '预算特定部门ID',
  `cost_budget_department_id` int(11) DEFAULT NULL COMMENT '支出预算部门ID',
  `cost_type_id` int(11) NOT NULL DEFAULT 0 COMMENT '费用类别id',
  `budget_detail_id` varchar(20) NOT NULL DEFAULT '' COMMENT '关联项目预算ID',
  `cost_id` varchar(20) NOT NULL DEFAULT '' COMMENT '关联项目预算明细ID',
  `expend_sn` varchar(255) NOT NULL COMMENT '支出单号',
  `expend_reason` varchar(500) NOT NULL DEFAULT '' COMMENT '付款事由',
  `account_id` int(11) NOT NULL DEFAULT 0 COMMENT '付款账户id',
  `service_line_id` int(11) NOT NULL DEFAULT 0 COMMENT '业务线id',
  `product_id` int(11) NOT NULL DEFAULT 0 COMMENT '产品id',
  `project_id` int(11) NOT NULL DEFAULT 0 COMMENT '项目id',
  `store_id` varchar(255) NOT NULL DEFAULT '' COMMENT '单店，多个用逗号连接',
  `expend_type_id` varchar(20) NOT NULL COMMENT '支出类型：1业务支出 YW；2个人报销 GR；3中后台费用 ZH',
  `expend_amount` decimal(10,2) NOT NULL DEFAULT 0.00 COMMENT '付款金额',
  `payment_type_id` int(11) NOT NULL DEFAULT 0 COMMENT '付款方式id',
  `payment_date` varchar(255) DEFAULT NULL COMMENT '付款日期',
  `belong_month` varchar(255) DEFAULT NULL COMMENT '所属月份',
  `supplier_name` varchar(255) NOT NULL DEFAULT '' COMMENT '收款人全称',
  `bank_account` varchar(255) NOT NULL DEFAULT '' COMMENT '银行账号',
  `open_bank` varchar(255) NOT NULL DEFAULT '' COMMENT '开户行',
  `supplier_id` int(11) NOT NULL DEFAULT 0 COMMENT '供应商id',
  `remarks` varchar(1000) NOT NULL DEFAULT '' COMMENT '备注',
  `sp_no` varchar(255) NOT NULL DEFAULT '' COMMENT '审批编号',
  `sp_status` tinyint(4) NOT NULL DEFAULT 0 COMMENT '审批状态',
  `add_time` datetime NOT NULL DEFAULT current_timestamp() COMMENT '添加时间',
  `userid` varchar(255) NOT NULL DEFAULT '' COMMENT '申请人id',
  `is_delete` tinyint(4) NOT NULL DEFAULT 1 COMMENT '是否删除 1未删除 0已删除',
  `is_claim` tinyint(4) NOT NULL DEFAULT 0 COMMENT '是否已付 1已付 0未付',
  `file_type` varchar(64) NOT NULL DEFAULT 'pic' COMMENT '文件类型 pic:图片 file:文件',
  `activity_id` int(11) NOT NULL DEFAULT 0 COMMENT '关联活动ID',
  `activity_budget_ids` varchar(255) NOT NULL DEFAULT '' COMMENT '关联活动预算IDs',
  `jk_expend_id` int(11) DEFAULT NULL COMMENT '借款id',
  `borrow_reason` varchar(255) NOT NULL DEFAULT '' COMMENT '借款事由',
  `return_time` varchar(255) NOT NULL DEFAULT '' COMMENT '归还时间',
  `is_offset` tinyint(4) NOT NULL DEFAULT 0 COMMENT '是否已冲抵 1是 0否',
  `store_cost_type` varchar(50) NOT NULL DEFAULT '' COMMENT '单店支出费用类别',
  `actual_amount` decimal(10,2) NOT NULL DEFAULT 0.00 COMMENT '实际支出金额',
  `is_bookkeeping` tinyint(4) NOT NULL DEFAULT 0 COMMENT '是否是记账 1：是 0：否，是记账的时候不用审批 只做记录',
  `product_order_salary_id` varchar(64) DEFAULT NULL COMMENT '关联劳动产品订单ID',
  `is_save` tinyint(4) NOT NULL DEFAULT 0 COMMENT '是否暂存  1是 0否',
  `new_budget_id` int(11) DEFAULT NULL COMMENT '新版财务预算模块ID\\\\n，查余额使用',
  `new_cost_type_id` int(11) DEFAULT NULL COMMENT '新版财务预算费用类别ID',
  `cmb_status` enum('待处理','处理中','待审批','支付成功','支付失败','支付撤销','审批否决','审批过期','支付退票','挂账','处理超时') DEFAULT NULL COMMENT '银行处理状态(中文枚举)',
  `cmb_result_time` varchar(32) DEFAULT NULL COMMENT '终态时间',
  `receipt_file_url` varchar(512) DEFAULT NULL COMMENT '回执PDF的OSS URL',
  `receipt_printid` varchar(128) DEFAULT NULL COMMENT '回执打印任务ID',
  `bank_reason` varchar(255) DEFAULT NULL COMMENT '银行原始原因文本（退票rtnNar/撤销/挂账说明）',
  `bank_reason_code` varchar(32) DEFAULT NULL COMMENT '银行原因代码（退票rtnCod）',
  `bank_result_amount` decimal(18,2) DEFAULT NULL COMMENT '银行结果金额（退票trsAmt，元）',
  `bank_result_time` varchar(32) DEFAULT NULL COMMENT '银行结果时间（ISO8601，normalize_bank_time 归一化）',
  PRIMARY KEY (`expend_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=11896 DEFAULT CHARSET=utf8mb4 COMMENT='OA-付款表';

-- ----------------------------
