-- Table structure for guohua_rel_policy_social_account_bak_20260128
-- ----------------------------
DROP TABLE IF EXISTS `guohua_rel_policy_social_account_bak_20260128`;
CREATE TABLE `guohua_rel_policy_social_account_bak_20260128` (
  `social_account_id` int(11) NOT NULL AUTO_INCREMENT COMMENT '社会保险id',
  `account_id` int(11) DEFAULT NULL COMMENT '主体id',
  `account_code` varchar(255) DEFAULT NULL COMMENT '主体编号',
  `company_injury_rate` varchar(32) DEFAULT NULL COMMENT '企业工伤',
  `company_old_rate` varchar(32) DEFAULT NULL COMMENT '企业养老',
  `company_medicine_rate` varchar(32) DEFAULT NULL COMMENT '企业医疗',
  `company_work_rate` varchar(32) DEFAULT NULL COMMENT '企业失业',
  `company_fund_rate` varchar(32) NOT NULL DEFAULT '' COMMENT '企业公积金比例5%-12%',
  `company_medicine_heavy_rate` varchar(32) NOT NULL DEFAULT '' COMMENT '企业大病医疗比例',
  `our_injury_rate` varchar(32) DEFAULT NULL COMMENT '自身工伤',
  `our_old_rate` varchar(32) DEFAULT NULL COMMENT '自身养老',
  `our_medicine_rate` varchar(32) DEFAULT NULL COMMENT '自身医疗',
  `our_medicine_extra_amount` decimal(10,2) DEFAULT 0.00 COMMENT '自身医疗额外金额',
  `our_medicine_heavy_rate` varchar(32) DEFAULT NULL COMMENT '自身大病医疗',
  `our_work_rate` varchar(32) DEFAULT NULL COMMENT '自身失业',
  `our_fund_rate` varchar(32) DEFAULT NULL COMMENT '自身公积金比例5%-12%',
  `company_total_rate` varchar(32) DEFAULT NULL COMMENT '企业五险合计',
  `our_total_rate` varchar(32) DEFAULT NULL COMMENT '个人五险合计',
  `city_name` varchar(255) DEFAULT NULL COMMENT '城市名--废弃',
  `min_money` decimal(10,2) DEFAULT 0.00 COMMENT '最低薪资',
  `min_base` decimal(10,2) DEFAULT 0.00 COMMENT '最低基数',
  `company_medical_base` decimal(10,2) DEFAULT 0.00 COMMENT '企业医疗基数',
  `fund_base` decimal(10,2) DEFAULT 0.00 COMMENT '公积金缴费基数',
  `social_security_base` decimal(10,2) NOT NULL DEFAULT 0.00 COMMENT '社保缴纳基数--废弃',
  `old_base` decimal(10,2) DEFAULT 0.00 COMMENT '养老基数',
  `medical_base` decimal(10,2) DEFAULT 0.00 COMMENT '医疗基数',
  `injury_base` decimal(10,2) DEFAULT 0.00 COMMENT '工伤基数',
  `work_base` decimal(10,2) DEFAULT 0.00 COMMENT '失业基数',
  `social_start_date` int(11) DEFAULT NULL COMMENT '社保增减员开始日期',
  `social_end_date` int(11) DEFAULT NULL COMMENT '社保增增员结束日期',
  `fund_start_date` int(11) DEFAULT NULL COMMENT '公积金增减员开始日期',
  `fund_end_date` int(11) DEFAULT NULL COMMENT '公积金减员结束日期',
  `start_date` date DEFAULT NULL COMMENT '生效日期',
  `social_remarks` varchar(255) DEFAULT NULL COMMENT '社保备注',
  `remarks` varchar(255) DEFAULT NULL COMMENT '备注',
  `is_delete` tinyint(4) DEFAULT 1 COMMENT '1未删除 2已删除',
  `status` tinyint(4) NOT NULL DEFAULT 0 COMMENT '状态：0、未生效 1、已生效 2、已失效',
  `add_userid` varchar(64) NOT NULL DEFAULT '' COMMENT '修改人',
  `add_time` datetime NOT NULL DEFAULT current_timestamp() COMMENT '添加时间',
  PRIMARY KEY (`social_account_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=43 DEFAULT CHARSET=utf8mb4 COMMENT='社保缴费比例动态配置表';

-- ----------------------------
