-- Table structure for kpi_sales_commission_alloc_line
-- ----------------------------
DROP TABLE IF EXISTS `kpi_sales_commission_alloc_line`;
CREATE TABLE `kpi_sales_commission_alloc_line` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `detail_id` bigint(20) NOT NULL COMMENT '主表 kpi_sales_commission_monthly_detail.id',
  `stat_month` char(7) NOT NULL COMMENT 'YYYY-MM',
  `payment_confirm_id` int(11) NOT NULL COMMENT '认款ID',
  `source_ref` varchar(128) NOT NULL COMMENT '子项来源键',
  `alloc_seq` int(11) NOT NULL DEFAULT 0 COMMENT '序号',
  `payment_plan_id` int(11) DEFAULT NULL COMMENT '回款计划ID',
  `bill_detail_id` int(11) DEFAULT NULL COMMENT '开票明细ID',
  `contract_id` int(11) DEFAULT NULL COMMENT '子合同ID',
  `customer_id` int(11) DEFAULT NULL COMMENT '子客户ID',
  `received_amount` decimal(11,2) NOT NULL DEFAULT 0.00 COMMENT '子项分摊服务费',
  `sales_user_id` varchar(64) DEFAULT NULL,
  `sales_user_name` varchar(64) DEFAULT NULL,
  `customer_name` varchar(255) DEFAULT NULL,
  `customer_source` varchar(32) DEFAULT NULL,
  `employ_type` varchar(16) DEFAULT NULL,
  `light_disability_num` int(11) DEFAULT NULL,
  `light_quote_monthly` decimal(11,2) DEFAULT NULL,
  `severe_disability_num` int(11) DEFAULT NULL,
  `severe_quote_monthly` decimal(11,2) DEFAULT NULL,
  `dispatch_fee_monthly` decimal(11,2) DEFAULT NULL,
  `contract_sign_type` varchar(16) DEFAULT NULL,
  `sign_period_months` int(11) DEFAULT NULL,
  `channel_rebate_percent` decimal(11,4) DEFAULT NULL,
  `channel_rebate_source` tinyint(4) DEFAULT NULL,
  `channel_rebate_amount` decimal(11,2) DEFAULT NULL,
  `channel_commission_rate` decimal(11,4) DEFAULT NULL,
  `person_months` decimal(11,4) DEFAULT NULL,
  `monthly_price_after_channel` decimal(11,2) DEFAULT NULL,
  `commission_rule_id` int(11) DEFAULT NULL,
  `commission_rate` decimal(11,2) DEFAULT NULL,
  `operation_cost_amount` decimal(11,2) DEFAULT NULL,
  `commission_amount` decimal(11,2) DEFAULT NULL,
  `amount_after_all_cost` decimal(14,2) DEFAULT NULL,
  `team_manager_commission` decimal(14,2) DEFAULT NULL,
  `calc_remark` varchar(500) DEFAULT NULL,
  `split_mode` varchar(32) DEFAULT NULL,
  `remark` varchar(500) DEFAULT NULL,
  `create_time` datetime NOT NULL DEFAULT current_timestamp(),
  `update_time` datetime DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_detail_plan` (`detail_id`,`payment_plan_id`),
  KEY `idx_detail_id` (`detail_id`),
  KEY `idx_payment_confirm` (`payment_confirm_id`),
  KEY `idx_stat_month` (`stat_month`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='销售提成拆分子项明细';

-- ----------------------------
