-- Table structure for kpi_sales_commission_monthly_detail
-- ----------------------------
DROP TABLE IF EXISTS `kpi_sales_commission_monthly_detail`;
CREATE TABLE `kpi_sales_commission_monthly_detail` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `stat_month` char(7) NOT NULL COMMENT '统计月份 YYYY-MM',
  `team_name` varchar(100) NOT NULL DEFAULT '' COMMENT '团队',
  `sales_user_id` varchar(64) NOT NULL DEFAULT '' COMMENT '销售企业微信userid',
  `sales_user_name` varchar(50) NOT NULL DEFAULT '' COMMENT '销售姓名',
  `customer_source` varchar(50) NOT NULL DEFAULT '' COMMENT '客户来源（自销/老渠道老客户/渠道等）',
  `customer_id` bigint(20) NOT NULL DEFAULT 0 COMMENT '客户ID',
  `customer_name` varchar(200) NOT NULL DEFAULT '' COMMENT '客户名称',
  `employ_type` varchar(20) NOT NULL DEFAULT '' COMMENT '直雇/派遣',
  `light_disability_num` int(11) NOT NULL DEFAULT 0 COMMENT '轻残人数',
  `light_quote_monthly` decimal(12,2) NOT NULL DEFAULT 0.00 COMMENT '轻残报价人月单价',
  `severe_disability_num` int(11) NOT NULL DEFAULT 0 COMMENT '重残人数',
  `severe_quote_monthly` decimal(12,2) NOT NULL DEFAULT 0.00 COMMENT '重残报价人月单价',
  `dispatch_fee_monthly` decimal(12,2) NOT NULL DEFAULT 0.00 COMMENT '派遣费人月',
  `contract_start_date` date DEFAULT NULL COMMENT '合同开始日期',
  `contract_end_date` date DEFAULT NULL COMMENT '合同结束日期',
  `amount_year1` decimal(14,2) NOT NULL DEFAULT 0.00 COMMENT '第一年协议金额',
  `amount_year2` decimal(14,2) NOT NULL DEFAULT 0.00 COMMENT '第二年协议金额',
  `amount_year3` decimal(14,2) NOT NULL DEFAULT 0.00 COMMENT '第三年协议金额',
  `total_contract_amount` decimal(14,2) NOT NULL DEFAULT 0.00 COMMENT '合计合同签单金额',
  `payment_method` varchar(50) NOT NULL DEFAULT '' COMMENT '付款方式',
  `received_amount` decimal(14,2) NOT NULL DEFAULT 0.00 COMMENT '到账金额',
  `received_date` date DEFAULT NULL COMMENT '到账日期',
  `contract_sign_type` varchar(32) NOT NULL DEFAULT '' COMMENT '提成类型原文（新签/续签/续签提成等）',
  `contract_type` varchar(20) NOT NULL DEFAULT '' COMMENT '合同类型 new/renew',
  `sign_period_months` int(11) NOT NULL DEFAULT 0 COMMENT '签约周期（月）',
  `channel_commission_rate` decimal(8,4) NOT NULL DEFAULT 0.0000 COMMENT '渠道提成比例(小数如0.2)',
  `channel_rebate_amount` decimal(14,2) NOT NULL DEFAULT 0.00 COMMENT '返款金额（给渠道的）',
  `channel_rebate_source` tinyint(4) NOT NULL DEFAULT 0 COMMENT '渠道返款比例来源：1本笔返款申请 2客户最新返款申请 3合同 4客户 5渠道 6系统默认 0未命中',
  `person_months` decimal(14,4) NOT NULL DEFAULT 0.0000 COMMENT '本笔到账对应人月数',
  `monthly_price_after_channel` decimal(12,4) NOT NULL DEFAULT 0.0000 COMMENT '扣除渠道后人均月单价',
  `commission_rule_id` bigint(20) DEFAULT NULL COMMENT '匹配到的 kpi_commission_rule.id',
  `commission_rate` decimal(5,2) NOT NULL DEFAULT 0.00 COMMENT '提成比例(%)来自规则表',
  `operation_cost_amount` decimal(14,2) NOT NULL DEFAULT 0.00 COMMENT '运营成本金额',
  `amount_after_all_cost` decimal(14,2) NOT NULL DEFAULT 0.00 COMMENT '扣除所有成本后金额（计提基数）',
  `commission_amount` decimal(14,2) NOT NULL DEFAULT 0.00 COMMENT '提成金额',
  `overage_reward_amount` decimal(14,2) NOT NULL DEFAULT 0.00 COMMENT '超额奖励加成金额',
  `bonus_pool_accum` decimal(14,2) NOT NULL DEFAULT 0.00 COMMENT '中心奖金池累计',
  `team_manager_commission` decimal(14,2) NOT NULL DEFAULT 0.00 COMMENT '团队经理团队提成',
  `business_type` varchar(20) NOT NULL DEFAULT '' COMMENT '业务类型 direct/channel',
  `remark` varchar(500) NOT NULL DEFAULT '' COMMENT '备注',
  `calc_remark` varchar(500) NOT NULL DEFAULT '' COMMENT '系统计算说明',
  `source_ref` varchar(128) NOT NULL DEFAULT '' COMMENT '来源幂等键（同月唯一）',
  `payment_confirm_id` int(11) DEFAULT NULL COMMENT '认款ID',
  `is_skip_commission` tinyint(4) NOT NULL DEFAULT 0 COMMENT '1=不计提',
  `is_manual_add` tinyint(4) NOT NULL DEFAULT 0 COMMENT '1=手工补录',
  `create_time` datetime DEFAULT current_timestamp() COMMENT '创建时间',
  `update_time` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp() COMMENT '更新时间',
  `is_split` tinyint(4) NOT NULL DEFAULT 0 COMMENT '是否拆分子项汇总',
  `alloc_line_count` int(11) NOT NULL DEFAULT 0 COMMENT '子项条数',
  `split_mode` varchar(32) DEFAULT NULL COMMENT '拆分模式',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_kpi_scd_month_source_ref` (`stat_month`,`source_ref`) USING BTREE,
  KEY `idx_kpi_scd_month_sales` (`stat_month`,`sales_user_name`) USING BTREE,
  KEY `idx_kpi_scd_month_userid` (`stat_month`,`sales_user_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=21563 DEFAULT CHARSET=utf8mb4 COMMENT='销售提成月度明细表';

-- ----------------------------
