-- Table structure for policy_disability_insurance
-- ----------------------------
DROP TABLE IF EXISTS `policy_disability_insurance`;
CREATE TABLE `policy_disability_insurance` (
  `policy_id` int(11) NOT NULL AUTO_INCREMENT COMMENT '政策id',
  `department_id` int(10) NOT NULL DEFAULT 0 COMMENT '部门id',
  `province_id` int(10) NOT NULL DEFAULT 0 COMMENT '所在省',
  `city_id` int(10) NOT NULL DEFAULT 0 COMMENT '所在城市',
  `disabled_phone` varchar(255) NOT NULL DEFAULT '' COMMENT '残联电话',
  `is_levy` tinyint(4) NOT NULL DEFAULT 1 COMMENT '是否强制征收税款  1是 0否',
  `department_levy` varchar(32) NOT NULL DEFAULT '' COMMENT '征收部门',
  `policy_caliber_levy` varchar(255) NOT NULL DEFAULT '' COMMENT '政策征收口径',
  `paid_in_caliber_levy` varchar(255) NOT NULL DEFAULT '' COMMENT '实缴征收口径',
  `levy_rate` varchar(255) NOT NULL DEFAULT '' COMMENT '征收比例',
  `formula_levy` varchar(500) NOT NULL DEFAULT '' COMMENT '征收公式',
  `policy_caliber_levy_content` varchar(255) NOT NULL COMMENT '政策征收描述(政策截图、文件号、链接)',
  `policy_caliber_code` varchar(255) NOT NULL DEFAULT '' COMMENT '政策补贴相关文件号',
  `principle_payment` varchar(255) NOT NULL DEFAULT '' COMMENT '跨地区缴纳原则/资料文件',
  `content` text NOT NULL COMMENT '残疾人申报方式和审核资料',
  `inspect_annually_range` varchar(255) NOT NULL DEFAULT '' COMMENT '残保金年审时间段',
  `payment_date_range` varchar(255) NOT NULL DEFAULT '' COMMENT '缴费时间段',
  `disabled_payment_method` varchar(255) NOT NULL DEFAULT '' COMMENT '残保金缴纳方式(1地税账户申报缴纳  2电子税务网上缴纳 3电子税务缴纳或大厅)',
  `year` varchar(255) NOT NULL DEFAULT '' COMMENT '所在年份',
  `quarter` varchar(255) NOT NULL DEFAULT '' COMMENT '季度',
  `is_delete` tinyint(4) NOT NULL DEFAULT 1 COMMENT '是否删除 1未删除 0已删除',
  `add_time` datetime NOT NULL DEFAULT current_timestamp() COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp() COMMENT '更新时间',
  `add_userid` varchar(255) NOT NULL DEFAULT '' COMMENT '添加人',
  `update_userid` varchar(255) NOT NULL DEFAULT '' COMMENT '更新人',
  `is_pre_tax` varchar(255) NOT NULL DEFAULT '' COMMENT '是否是税前工资 1是 0 否',
  `old_rate` varchar(255) NOT NULL DEFAULT '' COMMENT '养老保险',
  `work_rate` varchar(255) NOT NULL DEFAULT '' COMMENT '失业保险',
  `injury_rate` varchar(255) NOT NULL DEFAULT '' COMMENT '工伤保险',
  `medicine_rate` varchar(255) NOT NULL DEFAULT '' COMMENT '医疗保险',
  `total_rate` varchar(255) NOT NULL DEFAULT '' COMMENT '五险合计',
  `fund` varchar(255) NOT NULL COMMENT '是否缴纳公积金  1是  0否',
  `dispatch` varchar(255) NOT NULL DEFAULT '' COMMENT '是否支持派遣   1是 0否',
  `supplement` varchar(255) NOT NULL COMMENT '是否支持补缴  1是  0否',
  `weight` varchar(255) NOT NULL DEFAULT '' COMMENT '一重是否可抵扣两轻  1是 0否',
  `remarks` varchar(255) NOT NULL DEFAULT '' COMMENT '备注',
  `fund_remarks` varchar(255) NOT NULL DEFAULT '' COMMENT '强制缴纳备注',
  `dispatch_remarks` varchar(255) NOT NULL DEFAULT '' COMMENT '派遣备注',
  `supplement_remarks` varchar(255) NOT NULL DEFAULT '' COMMENT '缴纳备注',
  `weight_remarks` varchar(255) NOT NULL DEFAULT '' COMMENT '重残抵扣备注',
  `principle_payment_remarks` varchar(255) NOT NULL DEFAULT '' COMMENT '跨地区缴纳原则/资料文件备注',
  `customer_city_id` varchar(255) NOT NULL DEFAULT '0' COMMENT '客户关联城市id',
  `min_base` varchar(255) NOT NULL DEFAULT '' COMMENT '最低基数',
  `min_money` varchar(255) NOT NULL DEFAULT '' COMMENT '最低薪资',
  PRIMARY KEY (`policy_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=51 DEFAULT CHARSET=utf8mb4 COMMENT='残保金缴纳政策表';

-- ----------------------------
