-- Table structure for psc_smart_plan_editable_record
-- ----------------------------
DROP TABLE IF EXISTS `psc_smart_plan_editable_record`;
CREATE TABLE `psc_smart_plan_editable_record` (
  `editable_id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '记录ID',
  `plan_no` varchar(64) NOT NULL DEFAULT '' COMMENT '方案编号',
  `plan_title` varchar(255) NOT NULL DEFAULT '' COMMENT '方案标题',
  `plan_token` varchar(64) NOT NULL DEFAULT '' COMMENT '第一步可编辑快照token',
  `company_name` varchar(255) NOT NULL DEFAULT '' COMMENT '客户名称',
  `customer_id` int(11) NOT NULL DEFAULT 0 COMMENT '客户ID',
  `region_code` varchar(16) NOT NULL DEFAULT '' COMMENT '用工地区编码',
  `region_name` varchar(255) NOT NULL DEFAULT '' COMMENT '用工所在地',
  `product_code` varchar(64) NOT NULL DEFAULT '' COMMENT '推荐产品编码',
  `product_name` varchar(255) NOT NULL DEFAULT '' COMMENT '推荐产品名称',
  `store_ids` varchar(500) NOT NULL DEFAULT '' COMMENT '匹配基地ID',
  `store_names` varchar(1000) NOT NULL DEFAULT '' COMMENT '匹配基地名称',
  `employee_count` int(11) NOT NULL DEFAULT 0 COMMENT '在职职工人数',
  `existing_light_count` int(11) NOT NULL DEFAULT 0 COMMENT '自有轻残',
  `existing_heavy_count` int(11) NOT NULL DEFAULT 0 COMMENT '自有重残',
  `plan_light_count` int(11) NOT NULL DEFAULT 0 COMMENT '方案轻残',
  `plan_heavy_count` int(11) NOT NULL DEFAULT 0 COMMENT '方案重残',
  `arrangement_ratio` decimal(6,3) NOT NULL DEFAULT 0.000 COMMENT '安置比例(百分数值,如1.5)',
  `baseline_deposit` decimal(14,2) NOT NULL DEFAULT 0.00 COMMENT '全年无新增安置残保金',
  `diff_deposit` decimal(14,2) NOT NULL DEFAULT 0.00 COMMENT '差额残保金',
  `subsidy` decimal(14,2) NOT NULL DEFAULT 0.00 COMMENT '补贴合计',
  `total_cost` decimal(14,2) NOT NULL DEFAULT 0.00 COMMENT '支出总计',
  `saving` decimal(14,2) NOT NULL DEFAULT 0.00 COMMENT '全年节约成本',
  `saving_rate` decimal(8,2) NOT NULL DEFAULT 0.00 COMMENT '节约率',
  `html_url` varchar(512) NOT NULL DEFAULT '' COMMENT 'HTML OSS地址',
  `pdf_url` varchar(512) NOT NULL DEFAULT '' COMMENT 'PDF OSS地址',
  `recalc` tinyint(4) NOT NULL DEFAULT 1 COMMENT '是否按输入项重算 1是 0否',
  `edited_payload_json` mediumtext DEFAULT NULL COMMENT '用户编辑后的可编辑数据JSON',
  `input_json` mediumtext DEFAULT NULL COMMENT '用户输入/参数快照',
  `result_json` mediumtext DEFAULT NULL COMMENT '生成结果快照(精简,不含HTML正文)',
  `metrics_json` mediumtext DEFAULT NULL COMMENT '指标数据JSON',
  `generation_trace_json` mediumtext DEFAULT NULL COMMENT 'LLM生成过程/trace',
  `generate_status` tinyint(4) NOT NULL DEFAULT 1 COMMENT '0生成中 1成功 2失败',
  `error_msg` varchar(1000) NOT NULL DEFAULT '' COMMENT '失败原因',
  `add_userid` varchar(64) NOT NULL DEFAULT '' COMMENT '生成用户ID',
  `add_username` varchar(128) NOT NULL DEFAULT '' COMMENT '生成用户名称',
  `session_id` varchar(128) NOT NULL DEFAULT '' COMMENT '会话ID',
  `is_delete` tinyint(4) NOT NULL DEFAULT 1 COMMENT '1未删除 0已删除',
  `add_time` datetime NOT NULL DEFAULT current_timestamp() COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp() COMMENT '更新时间',
  PRIMARY KEY (`editable_id`),
  KEY `idx_plan_token` (`plan_token`),
  KEY `idx_user_time` (`add_userid`,`add_time`),
  KEY `idx_company_time` (`company_name`,`add_time`)
) ENGINE=InnoDB AUTO_INCREMENT=41 DEFAULT CHARSET=utf8mb4 COMMENT='PSC智能方案简洁模式(可编辑)生成记录';

-- ----------------------------
